Refactor UI Component Styling in Jewel to Support defaults
JetBrains/jewel pull request #104
Opened 2023-08-31 12:23 UTC by lamba92

Retrieving text styles requires coroutines. This commit aims to allow the theme to start with text defaults and as soon as text styles get retrieved, the theme gets updated.

2023-08-31 13:52 UTC, rock3r requested changes

2023-08-31 13:52 UTC, rock3r commented on ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/BridgeUtils.kt
> +internal fun isLightTheme(): Boolean {
No, this is wrong and completely arbitrary. Use `JBColor.isBright` for this. The value is also already provided by `IntelliJThemeDefinition#isDark` and you should use that.

2023-08-31 13:52 UTC, rock3r commented on ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/Svg.kt
I just deleted this file because it wasn't used anywhere FYI

2023-08-31 13:52 UTC, rock3r commented on ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/SwingBridgeService.kt
> +    private val coroutineScope: CoroutineScope = CoroutineScope(SupervisorJob() + CoroutineName("JewelSwingBridge")),
Does this work correctly now on 232+?

2023-08-31 14:52 UTC, lamba92 commented on ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/Svg.kt
just tested, turns out, the current IJ dependency injection is not smart enough for this use case and will always choose the no-args constructor. Classic IJ!

2023-08-31 14:52 UTC, lamba92 commented on ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/SwingBridgeService.kt
> +    private val coroutineScope: CoroutineScope = CoroutineScope(SupervisorJob() + CoroutineName("JewelSwingBridge")),
just tested, the current IJ dependency injection is not smart enough for this use case and will always choose the no-args constructor. Classic IJ!

2023-08-31 15:00 UTC, rock3r commented on ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/SwingBridgeService.kt
> +    private val coroutineScope: CoroutineScope = CoroutineScope(SupervisorJob() + CoroutineName("JewelSwingBridge")),
Also probably worth suggesting a fix to you-know-who :D

2023-09-01 11:36 UTC, rock3r approved these changes

2023-09-01 12:32 UTC, merged