Decorated window with custom titlebar support
JetBrains/jewel pull request #173
Opened 2023-10-12 13:57 UTC by devkanro

2023-10-12 14:10 UTC, devkanro commented on core/src/main/kotlin/org/jetbrains/jewel/IconButton.kt
> +            onBackground(background) {
Some trick for show dark icon on dark background in light theme (Light theme with dark title bar), you can find the impl below

2023-10-12 14:10 UTC, devkanro commented on core/src/main/kotlin/org/jetbrains/jewel/IntelliJTheme.kt
> +internal val LocalOnDarkBackground = staticCompositionLocalOf<Boolean> {
I created a new composition local and not to use the LocalIsDarkTheme because we didn't change the theme's properties.

2023-10-12 14:10 UTC, devkanro commented on core/src/main/kotlin/org/jetbrains/jewel/IntelliJTheme.kt
> +    val locals = if (color.isSpecified && color.alpha == 1f) {
Ignore transparent colors, because we have no context to blend colors and get it is dark or not.

2023-10-12 14:10 UTC, devkanro commented on core/src/main/kotlin/org/jetbrains/jewel/IntelliJTheme.kt
> +fun onBackground(color: Color, content: @Composable () -> Unit) {
Function may should be renamed, but I can't give a better name

2023-10-12 14:10 UTC, devkanro commented on core/src/main/kotlin/org/jetbrains/jewel/IntelliJThemeDefinition.kt
> +    val extensionStyles: Array<ProvidedValue<*>>
I created this for controls in external module like DecoratedWindow and TitleBar

2023-10-12 14:10 UTC, devkanro commented on core/src/main/kotlin/org/jetbrains/jewel/util/ColorExtensions.kt
> +fun Color.isDark(): Boolean {
From IDEA

2023-10-12 14:10 UTC, devkanro commented on decorated-window/src/main/java/com/jetbrains/AccessibleAnnouncer.java
> +package com.jetbrains;
JBR generated codes

2023-10-13 13:37 UTC, rock3r requested changes

2023-10-13 13:37 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/util/ColorExtensions.kt
> +val Color.luminance: Double
Why not using the [`Color.luminance()`](https://developer.android.com/reference/kotlin/androidx/compose/ui/graphics/Color#(androidx.compose.ui.graphics.Color).luminance()) method?

2023-10-13 13:37 UTC, rock3r commented on decorated-window/src/main/java/com/jetbrains/AccessibleAnnouncer.java
> +package com.jetbrains;
Do we need everything? Can we slim it down to only what we actually need?

2023-10-13 13:37 UTC, rock3r commented on int-ui/int-ui-core/src/main/kotlin/org/jetbrains/jewel/intui/core/IntUiThemeDefinition.kt
> +data class IntUiThemeDefinition(
❌  we can't use data classes, as a library, because they break binary compatibility. See #83

2023-10-13 13:37 UTC, rock3r commented on int-ui/int-ui-core/src/main/kotlin/org/jetbrains/jewel/intui/core/IntUiThemeDefinition.kt
> +        copy(extensionStyles = extensionStyles + extensions)
I was thinking, this could allow multiple identical `ProvidedValue`s to be passed in. Wouldn't it make sense to use a `Set` to back the extension styles, so only the latest addition is retained? Should be easier to debug.

2023-10-13 13:37 UTC, rock3r commented on int-ui/int-ui-decorated-window/src/main/kotlin/org/jetbrains/jewel/intui/window/IntUiTheme.kt
> +fun IntUiThemeDefinition.titleBarStyle(svgLoader: SvgLoader, lightHeaderInLight: Boolean = false): TitleBarStyle =
I'm not a huge fan of taking the dark value from the theme and combining it with a boolean that is ignored if the theme is dark. What about making `TitleBarStyle` a sealed class that implements the various styles? It is a different pattern than we use elsewhere, but it's probably better for this specific case, as resulting API

2023-10-13 13:37 UTC, rock3r commented on int-ui/int-ui-decorated-window/src/main/kotlin/org/jetbrains/jewel/intui/window/styling/IntUiDecoratedWindowStyling.kt
> +@Stable data class IntUiDecoratedWindowStyle(
Please do not use `data class`. See #83

2023-10-13 13:37 UTC, rock3r commented on int-ui/int-ui-decorated-window/src/main/kotlin/org/jetbrains/jewel/intui/window/styling/IntUiDecoratedWindowStyling.kt
> +@Stable data class IntUiDecoratedWindowStyle(
PS: code style requires annotations to be on a separate line.

2023-10-13 13:37 UTC, rock3r commented on int-ui/int-ui-decorated-window/src/main/kotlin/org/jetbrains/jewel/intui/window/styling/IntUiDecoratedWindowStyling.kt
> +        )
For consistency with the rest of Jewel:

```suggestion
        @Composable fun light(
            colors: IntUiDecoratedWindowColors = IntUiDecoratedWindowColors.light(),
            metrics: IntUiDecoratedWindowMetrics = IntUiDecoratedWindowMetrics(),
        ) = IntUiDecoratedWindowStyle(colors, metrics)

        @Composable fun dark(
            colors: IntUiDecoratedWindowColors = IntUiDecoratedWindowColors.dark(),
            metrics: IntUiDecoratedWindowMetrics = IntUiDecoratedWindowMetrics(),
        ) = IntUiDecoratedWindowStyle(colors, metrics)
```

(the metrics default value should be in the metrics constructor)

2023-10-13 13:37 UTC, rock3r commented on int-ui/int-ui-decorated-window/src/main/kotlin/org/jetbrains/jewel/intui/window/styling/IntUiDecoratedWindowStyling.kt
> +@Stable data class IntUiDecoratedWindowStyle(
PPS: this and all child classes can be `Immutable` since all the children contain only primitive types or `@Immutable` values (`Color` and `Dp`)

2023-10-13 13:37 UTC, rock3r commented on int-ui/int-ui-decorated-window/src/main/kotlin/org/jetbrains/jewel/intui/window/styling/IntUiTitleBarStyling.kt
> +@Stable data class IntUiTitleBarStyle(
Same considerations as for `IntUiDecoratedWindowStyling`: code style, avoid data classes, etc

2023-10-13 13:37 UTC, rock3r commented on int-ui/int-ui-decorated-window/src/main/kotlin/org/jetbrains/jewel/intui/window/styling/IntUiTitleBarStyling.kt
> +            IntUiIconButtonColors(
Please add parameter names, it's really hard to figure out what's what when all parameters have the same value

2023-10-13 13:37 UTC, rock3r commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/Main.kt
> +            derivedStateOf {
We don't have backpressure problems, so there is no need to use `derivedStateOf`. See https://medium.com/androiddevelopers/jetpack-compose-when-should-i-use-derivedstateof-63ce7954c11b

2023-10-13 14:26 UTC, devkanro commented on core/src/main/kotlin/org/jetbrains/jewel/IntelliJTheme.kt
> +    CompositionLocalProvider(values = locals, content)
This is to avoid putting composable into conditional branches and avoid remembered state losed caused by conditional switching.

2023-10-13 15:23 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/IntelliJTheme.kt
> +    CompositionLocalProvider(values = locals, content)
Ah, I see. Yu have a good point.

2023-10-13 16:26 UTC, devkanro commented on decorated-window/src/main/java/com/jetbrains/AccessibleAnnouncer.java
> +package com.jetbrains;
Removed all unused component

2023-10-13 16:28 UTC, devkanro commented on int-ui/int-ui-core/src/main/kotlin/org/jetbrains/jewel/intui/core/IntUiThemeDefinition.kt
> +        copy(extensionStyles = extensionStyles + extensions)
ProvidedValue is not comparable...I think

2023-10-16 17:07 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/FocusableComponentState.kt
> +        isSwingCompatMode: Boolean = IntelliJTheme.isSwingCompatMode,
Why is this passed in here? I don't want to have a way for components to ignore the compat mode implicitly — for those which it makes no sense, we have in other cases reimplemented the when. The idea is that this function should always do the right thing in the base case, which is to respect the flag.

2023-10-16 17:07 UTC, rock3r commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/Main.kt
> +        var intTheme by remember { mutableStateOf(IntUiThemes.Light) }
`intUiTheme`? `theme`?

2023-10-17 02:22 UTC, devkanro commented on core/src/main/kotlin/org/jetbrains/jewel/FocusableComponentState.kt
> +        isSwingCompatMode: Boolean = IntelliJTheme.isSwingCompatMode,
Not all controls ignore hover and press events in swing compatibility mode. For example, DropDown in TitleBar has hover and press background.
I think the best way is to have each control handle the hover and press events by itself, like in devkanro/jewel#1

2023-10-17 02:22 UTC, devkanro commented on core/src/main/kotlin/org/jetbrains/jewel/styling/DropdownStyling.kt
> +            isSwingCompatMode = false,
Check here @rock3r

2023-10-17 08:27 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/FocusableComponentState.kt
> +        isSwingCompatMode: Boolean = IntelliJTheme.isSwingCompatMode,
I agree, what I was pointing to is that I'd rather keep this method unchanged, as components that want to behave differently can simply have their own, different implementation, instead of using this.

2023-10-17 08:42 UTC, rock3r approved these changes

2023-10-17 08:46 UTC, merged