Update SelectableLazyColumn for key separation and update Gradle wrapper
JetBrains/jewel pull request #216
Opened 2023-10-30 17:33 UTC by lamba92

Refactor SelectableLazyColumn and related classes, separating `selectionKey` and `uiKey`. `selectionKey` is used for selection and `uiKey` triggers recompositions. Also, upgraded Gradle wrapper to 8.4. This change improves re-composition handling and provides an easier way to control item selection without unnecessary recompositions.

2023-10-30 18:32 UTC, rock3r requested changes

2023-10-30 18:32 UTC, rock3r commented on settings.gradle.kts
> +    id("org.gradle.toolchains.foojay-resolver-convention") version "0.7.0"
Please avoid unrelated changes.

2023-10-31 08:54 UTC, Walingar requested changes
I don't see a reason for this change, so for now I am against of providing complicated logic

2023-10-31 08:54 UTC, Walingar commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/SelectableLazyColumn.kt
> +            .focusGroup()
There shouldn't be any focusable elements inside SelectableLazyColumn, otherwise `tab` behavior will work incorrectly, so we need to check only isFocused state and don't make it focusGroup

2023-10-31 08:54 UTC, Walingar commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/SelectableLazyListScope.kt
> +     * By default `[selectionKey] = [uiKey]`, but you can assign [uiKey] if you need to
But if we keep only uiKey as it was before, then with unchanged uiKey element can be recomposed if State is changed. 
Key is used mostly for keeping scroll in a proper position on items modification, not for skiping recomposition in this case

Can you please provide a usecase where you need different uiKey and selectionKey? Since example for Chips and Tree is wrong, since you need to provide not string but objects that hold State<String> if you want to change it.

2023-10-31 09:53 UTC, fscarponi commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/SelectableLazyColumn.kt
> +            .focusGroup()
Probably I'm missing something here, the only selectable element is the LazyColumn (due SEL is a wrapper).
if you are going to remove focusable from the LC, then you will have no way to send keybindings event to the component. 
BTW in most use cases, I doubt that users will not put something `clickable` inside the SLC, and if I'm not mind wrong, we cannot prevent that
Probably we can accept that and find a way to handle `TAB` key-event properly by moving in some way the focus to the next element

2023-10-31 10:20 UTC, fscarponi commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/SelectableLazyListScope.kt
> +     * By default `[selectionKey] = [uiKey]`, but you can assign [uiKey] if you need to
> Can you please provide a usecase where you need different uiKey and selectionKey
I can try to give you a reason: imagine you have a not so small item in the dataset, 
- probably you will handle the item key with a minimal key (as example, you can use a UUID as key)
- now something inside this item will change (or the whole item to)
- if you have the same key for both, your item will not be shown in the list; otherwise, you lose the selection because the key is not the same

2023-10-31 11:04 UTC, Walingar commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/SelectableLazyListScope.kt
> +     * By default `[selectionKey] = [uiKey]`, but you can assign [uiKey] if you need to
Sorry, I still don't get it. Let's just use selectionId as itemId then? It's the same.

> you lose the selection because the key is not the same

And this is expected behaviour, item is not the same, it shouldn't be selected. For sure, it depends on requirements, but this should be handled by SelectableLazyColumn itself then. I mean how to handle selection when selected items are removed

2023-10-31 12:37 UTC, lamba92 commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/SelectableLazyListScope.kt
> +     * By default `[selectionKey] = [uiKey]`, but you can assign [uiKey] if you need to
It is needed in case you want to decouple the selection from recompositions. Indeed having a state inside the item to pass would be optimal, but in the case of PKGS it is not possible. We have a huge complex model and all the data to construct the tree is not reactive (flows/states ecc...). Everytime there is a change in a single part of the model, the entirety of the model gets re-emitted.

We could transform a portion of the model from plain properties to reactive components but that would require a huge rewrite and would also mean a lot of issues with the IJ platform (not everything is easily transformed into a reactive component).

2023-10-31 12:38 UTC, Walingar commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/SelectableLazyListScope.kt
> +     * By default `[selectionKey] = [uiKey]`, but you can assign [uiKey] if you need to
So then you need to introduce ids for your items and use them as keys

2023-10-31 12:39 UTC, Walingar commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/SelectableLazyListScope.kt
> +     * By default `[selectionKey] = [uiKey]`, but you can assign [uiKey] if you need to
Otherwise, scrolling will be broken on recomposition also.

2023-10-31 12:40 UTC, lamba92 commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/SelectableLazyListScope.kt
> +        uiKey: Any = selectionKey,
What about `selectionKey` and `itemKey`?  I mean the first is for the selection, the second is passed to `LazyColumn` and there is called `itemKey`.

2023-10-31 12:41 UTC, lamba92 commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/SelectableLazyListScope.kt
> +    isActive: Boolean,
Nope, this PR is not about that

2023-10-31 12:41 UTC, lamba92 commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/tree/BuildTree.kt
> +        val uiId: Any?
up

2023-10-31 12:46 UTC, lamba92 commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/components/ChipsAndTree.kt
> +        }
It is a test for the changes. The objective of this PR is to allow to recompose when an item changes without loosing the selection. In other words, the selection should be on a subset of the data available in the item.

2023-10-31 12:48 UTC, lamba92 commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/components/ChipsAndTree.kt
> +            uiKey = { index -> listOfItems[index] },
The objective of this PR is to allow to recompose when an item changes without loosing the selection. In other words, the selection should be on a subset of the data available in the item.

2023-10-31 12:48 UTC, lamba92 commented on settings.gradle.kts
> +    id("org.gradle.toolchains.foojay-resolver-convention") version "0.7.0"
It is necessary to run reliably the sample. I will move it to another PR

2023-10-31 13:38 UTC, lamba92 commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/SelectableLazyListScope.kt
> +     * By default `[selectionKey] = [uiKey]`, but you can assign [uiKey] if you need to
removed!

2023-10-31 13:38 UTC, lamba92 commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-8.4-all.zip
reverted, see [PR#231](https://github.com/JetBrains/jewel/pull/231)

2023-10-31 13:38 UTC, lamba92 commented on samples/standalone/build.gradle.kts
> +}
reverted, see [PR#231](https://github.com/JetBrains/jewel/pull/231)

2023-10-31 13:38 UTC, lamba92 commented on settings.gradle.kts
> +    id("org.gradle.toolchains.foojay-resolver-convention") version "0.7.0"
reverted, see [PR#231](https://github.com/JetBrains/jewel/pull/231)

2023-10-31 13:43 UTC, lamba92 commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/SelectableLazyColumn.kt
> +            .focusGroup()
I think I agree with @Walingar. On the other hand we need to warn the user to not use focusable or clickable modifiers on items inside the list. A solution could be to add such modifiers with all their overloads as extension members of `SelectableLazyListScope` and mark such modifiers as errors using annotations.

2023-10-31 14:40 UTC, rock3r commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/components/ChipsAndTree.kt
> +        }
Yeah it's not something I would include in the sample for everyone though, especially since it's not something we want anyone to _actually_ be doing :P

2023-10-31 14:41 UTC, rock3r commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/components/ChipsAndTree.kt
> +        }
Please only keep this change locally while you develop.

2023-10-31 14:42 UTC, rock3r commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/components/ChipsAndTree.kt
> +            uiKey = { index -> listOfItems[index] },
> the selection should be on a subset of the data available in the item

And yet here the selection is _not_ based on the item data 🤔

2023-10-31 14:43 UTC, rock3r commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/SelectableLazyColumn.kt
> +            .focusGroup()
I don't know how that scales. I reckon a Lint check would the right way to go, but since we don't have that, a Detekt check would be good as well.

2023-10-31 19:36 UTC, closed without merging