Enable explicit API mode
JetBrains/jewel pull request #232
Opened 2023-10-31 16:48 UTC by rock3r

This PR enables the explicit API mode in the Kotlin compiler. This means that all public API must be explicitly annotated as such, and provide explicit return types, or the compilation will break. This ensures better API stability and avoids unexpected return types (it already caught something, which is fixed in this PR).

Since this PR is _immense_, know that it is:
 1. Enabling the explicit API mode
 2. Adding public modifiers and explicit return types until the project runs again
 3. Reformatting _everything_
 4. Cleaning up some minor style problems in code that was changed anyway
 5. Providing better error messages for missing composition locals, that point to the lack of theme (that code was impacted anyway from the rest of the changes)

2023-11-01 11:25 UTC, rock3r commented
Switching reviewer to @devkanro since @lamba92 is on vacation

2023-11-01 15:56 UTC, devkanro requested changes
The indents need be fixed.

2023-11-01 16:31 UTC, rock3r commented
All fixed :)

2023-11-01 17:30 UTC, devkanro reviewed
Some line breaks seems unnecessary, can you recheck those style? But I don't block this.

2023-11-01 17:30 UTC, devkanro commented on buildSrc/src/main/kotlin/IdeaConfiguration.kt
> +            .runCatching {
This line breaks seem unnecessary.

2023-11-01 17:30 UTC, devkanro commented on buildSrc/src/main/kotlin/jewel-ij-publish.gradle.kts
> +                when (supportedIJVersion()) {
Also this

2023-11-01 17:30 UTC, devkanro commented on buildSrc/src/main/kotlin/jewel-publish.gradle.kts
> +tasks.registering(Jar::class) {
Also this

2023-11-01 17:30 UTC, devkanro commented on buildSrc/src/main/kotlin/jewel.gradle.kts
> +    when {
This

2023-11-01 17:30 UTC, devkanro commented on buildSrc/src/main/kotlin/org/jetbrains/jewel/buildlogic/demodata/AndroidStudioReleasesReader.kt
> +            release.channel.lowercase().let {
This

2023-11-01 17:30 UTC, devkanro commented on buildSrc/src/main/kotlin/org/jetbrains/jewel/buildlogic/theme/IntUiThemeDescriptorReader.kt
> +            colors.entries
This

2023-11-01 17:30 UTC, devkanro commented on buildSrc/src/main/kotlin/org/jetbrains/jewel/buildlogic/theme/IntelliJThemeGeneratorPlugin.kt
> +            IntUiThemeDescriptorReader.readThemeFrom(themeDescriptor, className, ideaVersion.get(), url)
This

2023-11-01 17:30 UTC, devkanro commented on decorated-window/src/main/kotlin/org/jetbrains/jewel/window/DecoratedWindow.kt
> +                it.measure(contentConstraints.offset(vertical = -titleBarHeight - titleBarBorderHeight))
This

2023-11-01 17:30 UTC, devkanro commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/SelectableLazyColumn.kt
> +                    stickyHeader(entry.key, entry.contentType) {
Maybe this

2023-11-01 19:16 UTC, rock3r commented
Hopefully it's all fixed for real now :P

2023-11-02 02:12 UTC, devkanro approved these changes
LGTM

2023-11-02 02:12 UTC, merged