Fix icon don't be scaled after density changed
JetBrains/jewel pull request #239
Opened 2023-11-02 03:19 UTC by devkanro

<img width="499" alt="截屏2023-11-02 11 19 14" src="https://github.com/JetBrains/jewel/assets/9367842/5ec6f576-e0ef-4c72-81c7-445621bbc523">

Close #236 and resolve comments in #234

2023-11-02 03:30 UTC, devkanro commented on ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/BridgeUtils.kt
> +internal fun retrieveIdeaDensity(sourceDensity: Density): Density {
The component can't be passed here when used in `SwingBridgeService`, so I moved the density calcing out of `SwingBridgeService`.

But I found we call `retrieveIdeaDensity` in composable function, so I change to use the `LocalDensity.current`.

2023-11-02 03:30 UTC, devkanro commented on ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/SwingBridgeService.kt
> -            density = retrieveDensity(),
We can't calc the density in `SwingBridgeService` context, I move out it

2023-11-02 03:30 UTC, devkanro commented on ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/JewelComposePanel.kt
> +public fun JewelComposePanel(
I found the `com.intellij.platform.compose.JBComposePanel` in platform codes, but I think we need provide it in Jewel, so I create one with default theme, and other settings.

2023-11-02 03:30 UTC, devkanro commented on ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/JewelComposePanel.kt
> +public val LocalComponent: ProvidableCompositionLocal<JComponent> = staticCompositionLocalOf {
It copied from `com.intellij.platform.compose.JBComposePanel`.

Maybe it won't be used(we provided it in scope), or we will remove it in next release, so I add `@ExperimentalJewelApi` annotation for it.

2023-11-02 03:30 UTC, devkanro commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt
> +        val cacheKey = scope.acceptedHints.hashCode() * 31 + LocalDensity.current.hashCode()
The key of bug #236

2023-11-02 08:13 UTC, rock3r approved these changes

2023-11-02 08:13 UTC, rock3r commented on ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/JewelComposePanel.kt
> +public fun JewelComposePanel(
Note that Compose/Jewel-related code will be removed from 23.3 (and added back for 24.1) so `JBComposePanel` might not exist until then anyway. When it does exist, though, we should use the platform one.

2023-11-02 08:13 UTC, rock3r commented on ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/JewelComposePanel.kt
> +public val LocalComponent: ProvidableCompositionLocal<JComponent> = staticCompositionLocalOf {
I think we can omit it, since we don't use it. I prefer the scope, too

2023-11-02 08:13 UTC, rock3r commented
Leaving to @Walingar to ship

2023-11-02 08:22 UTC, devkanro commented on ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/JewelComposePanel.kt
> +public fun JewelComposePanel(
@rock3r I think the platform should not provide `JBComposePanel`, it should be provided by Jewel...

2023-11-02 08:24 UTC, rock3r commented on ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/JewelComposePanel.kt
> +public fun JewelComposePanel(
It will eventually be a moot distinction :)

2023-11-02 17:33 UTC, Walingar requested changes

2023-11-02 17:33 UTC, Walingar commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt
> +        val cacheKey = scope.acceptedHints.hashCode() * 31 + LocalDensity.current.hashCode()
Let's then use `density` local variable here

2023-11-02 17:33 UTC, Walingar commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt
> +        val cacheKey = scope.acceptedHints.hashCode() * 31 + LocalDensity.current.hashCode()
Let's surround it with remember(density, scope.acceptedHints)

2023-11-02 17:33 UTC, Walingar commented on ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/JewelComposePanel.kt
> +public interface ComposePanelScope {
Why do we need this scope? Let's use LocalComponent composition local and use it for retrieveIdeaDensity

2023-11-03 09:23 UTC, devkanro commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt
> +        val cacheKey = scope.acceptedHints.hashCode() * 31 + LocalDensity.current.hashCode()
Using remember may be more expensive. Calculating hashcode is not an expensive operation, which is why I didn't use remember before.

2023-11-03 09:24 UTC, devkanro commented on ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/JewelComposePanel.kt
> +public interface ComposePanelScope {
This is just to make the JewelComposePanel DSL more powerful

2023-11-03 10:53 UTC, Walingar commented on ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/JewelComposePanel.kt
> +public interface ComposePanelScope {
I'd suggest having either scope either LocalComponent, preferrably LocalComponent

2023-11-03 12:01 UTC, rock3r commented on ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/JewelComposePanel.kt
> +public interface ComposePanelScope {
I see the reasoning. Hadn't considered that. Let's only keep the composition local then, since we don't need the scope anymore.

2023-11-03 14:04 UTC, Walingar approved these changes

2023-11-03 14:04 UTC, merged