LazyTree - contiguous selection appearance fixed
JetBrains/jewel pull request #251
Opened 2023-11-21 10:18 UTC by fscarponi

`LazyTree` selection appearance for contiguous blocks has been fixed.

to achieve this, we check if the previous item key is `IN` the selected keys list.
To reduce the overhead, the selection Key collection has been changed from a `List` to a `Set` (default implementation is LinkedHashSet)

2023-11-21 11:25 UTC, rock3r requested changes

2023-11-21 11:25 UTC, rock3r commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/SelectableColumnOnKeyEvent.kt
> +        val newSelection = LinkedHashSet<Any>(max(initialIndex, state.selectedKeys.size)).apply {
Do you need this to be a linked hash set specifically? That is, do you care about the order?

2023-11-21 11:25 UTC, rock3r commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/SelectableColumnOnKeyEvent.kt
> +        state.selectedKeys = setOf(keys[targetIndex].key)
This seems incoherent with the rest, why is this not a linked hash set?

2023-11-21 11:25 UTC, rock3r commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/tree/BasicLazyTree.kt
> +                val upperCorners = flattenedTree.getOrNull(index - 1)?.id?.let {
I would name these two flags as `hasRoundedTopCorners` and `hasRoundedBottomCorners`

2023-11-21 11:25 UTC, rock3r commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/tree/BasicLazyTree.kt
> +                    topStart = if (upperCorners) elementBackgroundCornerSize else CornerSize(0.dp),
This if-else is repeated 4 times, I'd extract a small function for this. Something like:

```kotlin
private fun computeCornerSize(roundedSize: CornerSize, rounded: Boolean) =
    if (rounded) roundedSize else CornerSize(0.dp)
```

2023-11-21 11:25 UTC, rock3r commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/tree/DefaultTreeViewOnKeyEvent.kt
> +                                state.selectedKeys = setOf(parentNodeKey)
This and the next few usages also look dodgy, why not linked here?

2023-11-21 11:59 UTC, fscarponi commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/SelectableColumnOnKeyEvent.kt
> +        state.selectedKeys = setOf(keys[targetIndex].key)
it is by default under the hood

2023-11-21 12:00 UTC, fscarponi commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/SelectableColumnOnKeyEvent.kt
> +        state.selectedKeys = setOf(keys[targetIndex].key)
but it is ok to move it to a generic Set everywhere

2023-11-22 11:19 UTC, rock3r commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/SelectableColumnOnKeyEvent.kt
> +        state.selectedKeys = setOf(keys[targetIndex].key)
I'd rather use a generic Set unless you specifically need it to be linked. The implementation under the hood doesn't matter, and using the simple Set instead communicates different expectations.

2023-11-25 11:38 UTC, fscarponi commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/SelectableColumnOnKeyEvent.kt
> +        val newSelection = LinkedHashSet<Any>(max(initialIndex, state.selectedKeys.size)).apply {
we cannot move to generic Set, it does not have the required constructor, and I will not change the performance review made by @Walingar

2023-11-25 11:46 UTC, fscarponi commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/tree/DefaultTreeViewOnKeyEvent.kt
> +                                state.selectedKeys = setOf(parentNodeKey)
we don't need here a more performant constructor

2023-11-26 10:10 UTC, rock3r commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/SelectableColumnOnKeyEvent.kt
> +        val newSelection = LinkedHashSet<Any>(max(initialIndex, state.selectedKeys.size)).apply {
I'm sorry, I don't follow. Set is an interface, what constructor are you referring to? And what's the perf implication of using a non-linked hash set instead of a linked one?

2023-11-26 10:11 UTC, rock3r commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/tree/DefaultTreeViewOnKeyEvent.kt
> +                                state.selectedKeys = setOf(parentNodeKey)
I don't understand what this means

2023-11-26 20:30 UTC, fscarponi commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/tree/DefaultTreeViewOnKeyEvent.kt
> +                                state.selectedKeys = setOf(parentNodeKey)
nvm, probably I misunderstood

2023-11-27 07:32 UTC, rock3r commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/SelectableColumnOnKeyEvent.kt
> +        state.selectedKeys = keys.filterIsInstance<Selectable>().map { it.key }.toCollection(HashSet())
Why not `toSet()`?

2023-11-27 10:55 UTC, rock3r approved these changes

2023-11-27 11:21 UTC, merged