275 tabs for tabs strips does not allow custom content
JetBrains/jewel pull request #276
Opened 2023-12-18 16:39 UTC by fscarponi

2023-12-20 18:32 UTC, rock3r requested changes

2023-12-20 18:32 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/DefaultComponentStyling.kt
> +    public val toolWindowTabStyle: TabStyle,
Please keep the alphabetical sorting of the parameters

2023-12-20 18:32 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/component/TabStrip.kt
> +        public class ToolWindowTab(
Either this is `Toolwindow`, or the others are `EditorTab` and `CustomTab`, for consistency. I'd much rather the first. I am also not sure why you renamed `Default` to `Toolwindow`, aren't there any other tab implementations that use that style? I doubt it...

2023-12-20 18:32 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/component/TabStrip.kt
> +    public class Custom(
I disagree with this change. I think that "Custom" is not a real kind of tab. There are "regular" tabs (also known as `Default`), and `Editor` tabs. The difference between the two is the styling. Custom tabs are... what? Editor tabs? Non-editor tabs? Being custom is not a _style_ difference, it's a _contents_ difference.

I believe it would be much more productive to have the two variants from before (`Default` and `Editor`) but instead of carrying a `label` parameter, they carry a `content` parameter that is a composable lambda. That's the only change needed to implement what you want to achieve.

If you for whatever reason want to also keep the label-based DSL, you can easily implement it by calling the content-based API with a `Text(label)`.

2023-12-21 15:03 UTC, rock3r requested changes

2023-12-21 15:03 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/component/TabStrip.kt
> +            ).selectableGroup(),
```suggestion
            modifier = Modifier.horizontalScroll(scrollState)
                .scrollable(
                    orientation = Orientation.Vertical,
                    reverseDirection = ScrollableDefaults.reverseDirection(
                        LocalLayoutDirection.current,
                        Orientation.Vertical,
                        false,
                    ),
                    state = scrollState,
                    interactionSource = remember { MutableInteractionSource() },
                )
                .selectableGroup(),
```

2023-12-21 15:03 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/component/TabStrip.kt
> +                "org.jetbrains.jewel.ui.component.TabData.Default",
```suggestion
                "org.jetbrains.jewel.ui.component.TabData.Editor",
```

Re-read when you copy paste, please 😁

2023-12-21 15:03 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Tabs.kt
> +            Box(Modifier.alpha(labelAlpha)) {
Shouldn't `labelAlpha` be called `contentAlpha` if it affects the entirety of the content? And, are you sure this alpha affects all the content and not just the label?

2023-12-21 15:56 UTC, fscarponi commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Tabs.kt
> +            Box(Modifier.alpha(labelAlpha)) {
ok for content alpha naming...

about expected Behaviour. Who knows?
as example, i have a friend in cwm on the "Slider.kt" tab... but i don't see the icon! It appears (sometimes) when i hover the element with mouse
<img width="178" alt="image" src="https://github.com/JetBrains/jewel/assets/36624359/3c616b9d-6db1-41c2-bc38-2b3df460903b">
or if he moves between tabs, an empty box appears sometimes, but not always....
<img width="102" alt="image" src="https://github.com/JetBrains/jewel/assets/36624359/5b0b3b1e-113f-4459-9e86-513cb6afea83">

in another following case he is in a file, and the icon does not appear either that file is open and the editor is active...
<img width="547" alt="image" src="https://github.com/JetBrains/jewel/assets/36624359/6922219f-293c-4a37-9a78-c073cdf95625">

with this PR you can achieve this behavior... but spec does not mention how it should look...

my point is that we can hold it "as is" and monitor if it fits futures use cases...

2023-12-21 16:00 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Tabs.kt
> +            Box(Modifier.alpha(labelAlpha)) {
Yeah, fair enough. The Swing implementations are broken enough to begin with that it's almost impossible to figure out what the visual intention is. We can revisit later.

2023-12-21 16:05 UTC, rock3r commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Tabs.kt
>              TabData.Editor(
Doesn't look resolved (commit not pushed?)

2023-12-21 16:13 UTC, fscarponi commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Tabs.kt
>              TabData.Editor(
yea

2023-12-28 10:03 UTC, rock3r approved these changes

2023-12-28 10:03 UTC, merged