Add strikethrough markdown support
JetBrains/jewel pull request #325
Opened 2024-03-21 06:41 UTC by obask

Since it's inlined, the extension is added directly to the core module.

2024-03-22 10:32 UTC, rock3r reviewed
The PR looks good, but I would prefer if we didn't have extensions bundled in the core module. I know it's a bit more work to fully support inline extensions, but the skeleton should already be there. Can you extract the strikethrough code to an `extension-gfm-strikethrough` module?

2024-03-22 10:32 UTC, rock3r commented on settings.gradle.kts
> +findProject(":markdown:commonmark-extensions")?.name = "commonmark-extensions"
I'm not sure why this is added here. We don't have such a module in the project, as far as I can see

2024-04-02 14:17 UTC, rock3r commented
@obask this requires a rebase/cleanup after the latest changes :)

2024-07-19 10:34 UTC, rock3r commented
Now that #458 has added inline extensions support, it should be possible to complete the work on this as a separate module

2024-09-06 13:50 UTC, obask commented on markdown/extension/strikethrough/src/main/kotlin/org/jetbrains/jewel/markdown/extension/strikethrough/StrikethroughRendererExtension.kt
> +                                inlinesStyling.textStyle
not sure I'm taking the right style here...

2024-09-06 17:36 UTC, francisconoriega commented on markdown/extension/strikethrough/src/main/kotlin/org/jetbrains/jewel/markdown/extension/strikethrough/StrikethroughRendererExtension.kt
> +                    }
just fyi, you can use `builder.withStyle` to automatically get a push/pop of that style

```suggestion
                   val style =  inlinesStyling.textStyle
                                    .copy(textDecoration = TextDecoration.LineThrough)
                                    .toSpanStyle()
                                    .copy()
                                    
                    builder.withStyle(style) {
                                  val inlineMarkdowns = (inline as? WithInlineMarkdown)?.inlineContent ?: emptyList()
                                  for (markdown in inlineMarkdowns) {
                                      append(
                                          inlineRenderer.renderAsAnnotatedString(listOf(markdown), inlinesStyling, enabled = true)
                                      )
                                  }
                        }
                    }
```

2024-09-06 17:39 UTC, francisconoriega commented on markdown/extension/strikethrough/src/test/kotlin/org/jetbrains/jewel/markdown/extension/autolink/StrikethroughProcessorExtensionTest.kt
> +}
is this meant to be: 
```suggestion
class StrikethroughProcessorExtensionTest {
    // testing a simple case to assure wiring up our StrikethroughProcessorExtension works correctly
    @Test
    fun `~~ processed into strikethrough`() {
        val processor = MarkdownProcessor(listOf(StrikethroughProcessorExtension))
        val rawMarkDown = "~~fdsa~~"
        val processed = processor.processMarkdownDocument(rawMarkDown)
        val paragraph = processed.first() as MarkdownBlock.Paragraph

        assertTrue(paragraph.inlineContent.first() is InlineMarkdown.Strikethrough)
    }
}
```

2024-09-10 21:44 UTC, rock3r requested changes

2024-09-10 21:44 UTC, rock3r commented on markdown/extension/strikethrough/src/main/kotlin/org/jetbrains/jewel/markdown/extension/strikethrough/CustomStrikethroughNode.kt
> +        node.children().mapNotNull { it.toInlineMarkdownOrNull(processor, emptyList()) },
Shouldn't we pass the list of extensions, too? Otherwise, other inline extensions will be ignored.

2024-09-10 21:44 UTC, rock3r commented on markdown/extension/strikethrough/src/main/kotlin/org/jetbrains/jewel/markdown/extension/strikethrough/StrikethroughRendererExtension.kt
> +                                inlinesStyling.textStyle
Should be the right one 👍

2024-09-10 21:44 UTC, rock3r commented on markdown/extension/strikethrough/src/main/kotlin/org/jetbrains/jewel/markdown/extension/strikethrough/StrikethroughRendererExtension.kt
> +                                    .copy()
I don't think you need the extra copy

2024-09-10 21:44 UTC, rock3r commented on markdown/extension/strikethrough/src/main/kotlin/org/jetbrains/jewel/markdown/extension/strikethrough/StrikethroughRendererExtension.kt
> +}
Right now it's unused — you should follow @francisconoriega's suggestion above and use this :)

2024-10-11 10:30 UTC, obask commented
I'm not sure if passing `markdownProcessor` and `extensions` as separate args works well. Maybe we should just make extensions public or restructure it in some other way.

2024-10-11 10:38 UTC, rock3r commented
Given #600 will likely make inline extensions easier, I'd shelve this until that's done. What do you think?

Maybe we can revisit image loading in the meantime

2024-10-11 10:51 UTC, obask commented
> Given #600 will likely make inline extensions easier, I'd shelve this until that's done. What do you think?

Are you handling #600 yourself? I don't mind waiting, just didn't want stale comments to hang on this PR.

> Maybe we can revisit image loading in the meantime

SG! I can do images on or after Oct 16 if that's ok.

2024-10-11 10:54 UTC, rock3r commented
Yes, I have started. It will probably take me a couple weeks-ish to finish tho as I have a busy rest of the month.

Ok for the timing on images. We can also catch up in London.

2025-01-16 09:40 UTC, rock3r commented
Superseded by #748

2025-01-16 09:40 UTC, closed without merging