Use value classes for inline markdown #329
JetBrains/jewel pull request #331
Opened 2024-03-27 01:15 UTC by obask

This classes wrap CommonMark's nodes and preserve
a familiar API. Some tests were turned off because we don't use the same IR for string serialization.

Changing dataclasses to values classes for blocks
is coming in the next pull request.

2024-03-27 02:04 UTC, obask commented
I thought that it makes scrolling errors more prominent, but it looks exactly the same as before... not sure if the bug is in CfD or the way we represent lists or remember some nodes... which is probably not the case, because these nodes don't change during rendering at all.

2024-03-27 09:05 UTC, rock3r commented
You need to run the `apiDump` task for this to go green :)

2024-03-27 09:42 UTC, rock3r commented on markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/processing/MarkdownProcessor.kt
> +            // TODO: add support for LinkReferenceDefinition
Note that link reference definitions were purposefully ignored and inlined into their respective links, because they break the encapsulation of block-level models. I still think we should inline references and ignore LinkReferenceDefinitions, since they have no UI value nor representation.

2024-03-27 09:42 UTC, rock3r commented on markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/processing/MarkdownProcessor.kt
> +//        if (inlineMarkdown.isEmpty()) return null
This was done on purpose, too — there is no point in empty paragraphs for what the UI is concerned.

2024-03-27 09:42 UTC, rock3r commented on markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/processing/MarkdownProcessor.kt
> +        return org.jetbrains.jewel.markdown.MarkdownBlock.ListBlock.BulletList(children, isTight, bulletMarker)
This FQN seems left here by mistake

2024-03-27 09:42 UTC, rock3r commented on markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/rendering/DefaultInlineMarkdownRenderer.kt
> +                is InlineMarkdown.CustomNode -> error("InlineMarkdown.CustomNode render is not implemented")
I guess this is the entry point for inline renderer extensions when we build those...

2024-03-27 09:42 UTC, rock3r commented on markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/rendering/DefaultMarkdownBlockRenderer.kt
> +                else -> error("$block")
Would be nice to have a more meaningful error description here
```suggestion
                else -> error("Heading level ${block.level} not supported:\n$block")
```

2024-03-27 09:42 UTC, rock3r commented on markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/rendering/DefaultMarkdownBlockRenderer.kt
>          }
Missing the else case:
```suggestion
            6 -> render(block, styling.h6)
            else -> error("Heading level ${block.level} not supported:\n$block")
        }
```

2024-03-27 09:42 UTC, rock3r commented on markdown/core/src/test/kotlin/org/jetbrains/jewel/markdown/MarkdownProcessorDocumentParsingExtraTest.kt
> +    @org.junit.Ignore
Add import for `Ignore`

2024-03-27 09:42 UTC, rock3r commented on markdown/core/src/test/kotlin/org/jetbrains/jewel/markdown/MarkdownProcessorDocumentParsingTest.kt
> +    @Ignore("leading # is not supported yet")
Is this tracked somewhere?

2024-03-27 09:42 UTC, rock3r commented on markdown/core/src/test/kotlin/org/jetbrains/jewel/markdown/MarkdownProcessorDocumentParsingTest.kt
> +    @Ignore("need to update escapeInlineMarkdownChars implementation")
Ditto, is this tracked?

2024-03-27 10:45 UTC, rock3r requested changes
Forgot to mark as "request changes" :)

2024-03-30 05:10 UTC, obask commented on markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/rendering/DefaultInlineMarkdownRenderer.kt
> +                is InlineMarkdown.CustomNode -> error("InlineMarkdown.CustomNode render is not implemented")
yes, but I don't want to make this PR too big

2024-03-30 05:16 UTC, obask commented on markdown/core/src/test/kotlin/org/jetbrains/jewel/markdown/MarkdownProcessorDocumentParsingTest.kt
> +    @Ignore("leading # is not supported yet")
I actually rewrote how we do diffs in tests, so that's not needed

2024-03-30 05:17 UTC, obask commented on markdown/core/src/test/kotlin/org/jetbrains/jewel/markdown/MarkdownProcessorDocumentParsingExtraTest.kt
> +    @org.junit.Ignore
deleted. Sometimes I use it when I only need to ignore one test, because it makes it easier to resolve merges in the future

2024-03-30 05:18 UTC, obask commented on markdown/core/src/test/kotlin/org/jetbrains/jewel/markdown/MarkdownProcessorDocumentParsingTest.kt
> +    @Ignore("need to update escapeInlineMarkdownChars implementation")
deleted escapeInlineMarkdownChars implementation

2024-03-31 17:02 UTC, rock3r approved these changes
LGTM but has conflicts to solve first

2024-03-31 17:39 UTC, merged