Commonmark with value classes
JetBrains/jewel pull request #332
Opened 2024-03-27 07:27 UTC by obask

This PR includes both changes to block nodes as well as inline nodes.

For now the Processor is a noop, but it could be helpful later if we decide to offload some operations from the rendering pipeline. It would be easier to decide once we implement quick typing improvements.

2024-03-27 10:44 UTC, rock3r requested changes

2024-03-27 10:44 UTC, rock3r commented on markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/rendering/DefaultInlineMarkdownRenderer.kt
> +    private fun Builder.appendInlineMarkdownFrom(inlineMarkdown: Iterator<InlineMarkdown>, styling: InlinesStyling) {
Passing an `Iterator` around is kinda weird, because you can't know its state in advance. I'd prefer if it was receiving an `Iterable` instead so it can own its iterator

2024-03-27 10:44 UTC, rock3r commented on markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/rendering/DefaultMarkdownBlockRenderer.kt
> +            6 -> render(block, styling.h6)
Missing the else case

2024-03-27 10:44 UTC, rock3r commented on markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/rendering/DefaultMarkdownBlockRenderer.kt
> +                val mimeType = remember { MimeType.Known.fromMarkdownLanguageName(block.value.info) }
Could this be a property or function on our Fenced Block model? Value classes can have properties and functions IIRC. Ideally, I'd like to have less arcane ways to access useful information in cases like this. Our value classes can decorate and enrich the CommonMark models to make it easier to build extensions

2024-03-27 10:44 UTC, rock3r commented on markdown/extension/gfm-alerts/src/main/kotlin/org/jetbrains/jewel/markdown/extensions/github/alerts/GitHubAlertProcessorExtension.kt
> +//            }
Should we remove commented code?

2024-03-27 10:44 UTC, rock3r commented on markdown/extension/gfm-alerts/src/main/kotlin/org/jetbrains/jewel/markdown/extensions/github/alerts/GitHubAlertProcessorExtension.kt
> +            error("should use CustomNode parser instead")
I don't love APIs that have functions you must override but throw when you call them. Especially if the return type is nullable, wouldn't you just return null? Am I missing something?

2024-03-27 10:44 UTC, rock3r commented on markdown/extension/gfm-alerts/src/test/kotlin/org/jetbrains/jewel/markdown/extensions/github/alerts/GitHubAlertBlockExtensionTest.kt
> +            "Parsed node should be a Note node, but was $firstChild",
I think this message (and all similar following ones) should print firstChild.kind, not the whole firstChild

2024-03-30 08:12 UTC, closed without merging

2024-03-30 08:21 UTC, obask commented
addressed comments in https://github.com/JetBrains/jewel/commit/76b52827fbae2ebd6b42c8b31ba825c2853c958f but I can't create a chain of PRs, because I can't push to my branches

2024-03-30 08:22 UTC, obask commented on markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/rendering/DefaultInlineMarkdownRenderer.kt
> +    private fun Builder.appendInlineMarkdownFrom(inlineMarkdown: Iterator<InlineMarkdown>, styling: InlinesStyling) {
Iterator worked until I made things nullable... so I ended up simply using a `List`

2024-03-30 08:44 UTC, rock3r commented
@obask you have write permissions, that shouldn't happen. What does the error say? (we can troubleshoot in chat)