Clean up Commonmark API conventions
JetBrains/jewel pull request #338
Opened 2024-03-31 01:17 UTC by obask

- rename Bullet lists
- use one node type for Heading
- rename 'content' to 'children' if it points to other blocks

Also clean up tests to not use parenthesis,
becasue it breaks navigation in IDEA

2024-03-31 16:59 UTC, rock3r requested changes

2024-03-31 16:59 UTC, rock3r commented on markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/processing/MarkdownProcessor.kt
> +            .takeIf { level in 1..6 }
This is a pretty expensive check — we first convert the inline markdown, then create the Heading instance, then the 1..6 IntRange, and then we may be throwing it all away. A classic if would be better IMO:

```kotlin
private fun Heading.toMarkdownHeadingOrNull(): MarkdownBlock.Heading? {
  if (level < 1 || level > 6) return null
  return MarkdownBlock.Heading(contentsAsInlineMarkdown(), level)
}
```

2024-03-31 16:59 UTC, rock3r commented on markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/rendering/MarkdownStyling.kt
> +        public interface HN : WithInlinesStyling, WithUnderline {
Please make it sealed since it's not meant to be extended further

2024-03-31 16:59 UTC, rock3r commented on markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/MarkdownBlock.kt
> +        public data class BulletList(
I'm not a fan of this change, to be honest, and it was intentionally NOT called a `BulletList`. It's merely a question of taste from me, and I won't stop the PR because of it, since CommonMark also uses this poor naming 🙃

2024-03-31 17:19 UTC, obask commented on markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/processing/MarkdownProcessor.kt
> +            .takeIf { level in 1..6 }
I don't know why Idea added squiggly lines suggested an auto fix for this(I don't really trust compiler optimizations) but I like a simple if statement better too

2024-03-31 17:29 UTC, obask commented on markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/MarkdownBlock.kt
> +        public data class BulletList(
Changed it back since it's a more common name

2024-04-02 07:43 UTC, rock3r approved these changes

2024-04-02 07:49 UTC, merged