Set default color of Divider composable
JetBrains/jewel pull request #356
Opened 2024-04-15 19:51 UTC by YasserDbeis

The current color and fallback style create a transparent appearance for the Divider under Classic UI's Darkula theme. This change fixes such issue.

Manually verified that the color is correct for both new and Classic UI in all available themes.

2024-04-15 20:15 UTC, rock3r requested changes

2024-04-15 20:15 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Divider.kt
> +    color: Color = JewelTheme.globalColors.borders.normal,
This is not the right place for this — defaults should be set in the DividerStyle.color

2024-04-20 11:42 UTC, closed without merging

2024-04-20 11:46 UTC, rock3r commented
Since it's been a few days, I took the liberty to close this and implement the proper fix in #362

2024-04-24 21:40 UTC, YasserDbeis commented
Thank you!