Minor updates to the build files
JetBrains/jewel pull request #442
Opened 2024-07-09 17:44 UTC by rock3r

While I try to figure out what is happening with the IntelliJ Platform Gradle Plugin 2.0*, I cleaned up the build scripts a bit. This should ensure that:
1. We use the same major JDK version for buildSrc too
2. We enforce the language version in the standalone sample too (it should come from the Jewel plugin, but it doesn't — possibly because we set a toolchain in the module, too)
3. There are a couple less minor formatting issues than before
4. We have one less unused function

2024-07-10 13:27 UTC, lamba92 commented on buildSrc/build.gradle.kts
> +        languageVersion = JavaLanguageVersion.of(jdkLevel)
It should set it also for java. No need to duplicate it above

2024-07-10 14:25 UTC, lamba92 requested changes

2024-07-10 14:25 UTC, lamba92 commented on samples/standalone/build.gradle.kts
> +        languageVersion = JavaLanguageVersion.of(jdkLevel)
also here!

2024-07-15 09:19 UTC, hamen approved these changes

2024-07-15 12:42 UTC, merged