Add JewelLogger
JetBrains/jewel pull request #443
Opened 2024-07-10 09:56 UTC by hamen

# Overview

We added `JewelLogger`. It's heavily based on the [`LoggerRt`](https://raw.githubusercontent.com/JetBrains/intellij-community/master/platform/util-rt/src/com/intellij/openapi/diagnostic/LoggerRt.java) in IntelliJ.

Using the `JewelLogger` in a standalone application will print to `java.util.logger`.
Using it in an IDE Plugin will print to `idea.log`.

On paper, if you have something like this in your app
```
implementation ("ch.qos.logback:logback-classic:1.5.6")
implementation ("org.slf4j:slf4j-api:2.0.12")
```

`JewelLogger` should be able to hook into it.

# Usage

```
JewelLogger
    .getInstance("MyApp")
    .warn("my message")
```

# Maintenance

Every usage of `println` in the lib, in the IDE plugin and the standalone app have been replaced.

Closes #429

2024-07-10 12:09 UTC, rock3r reviewed
~~(not done reviewing yet, sorry, will do ASAP)~~

EDIT: done!

2024-07-10 13:48 UTC, rock3r requested changes

2024-07-10 13:48 UTC, rock3r commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/util/JewelLogger.kt
> +public abstract class JewelLogger {
Is it meant to not have debug and trace? We could use having those...

2024-07-10 13:48 UTC, rock3r commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/util/JewelLogger.kt
> +        public fun getInstance(clazz: Class<*>): JewelLogger = getInstance('#'.toString() + clazz.name)
Another interesting function to add at the top level maybe:

```kotlin
public inline fun <reified T : Any> T.myLogger(): Logger = JewelLogger.getInstance(T::class.java)
```

Makes using it in classes easy peasy:

```kotlin
class MyClass {
  private val logger = myLogger()
}
```

This models after the IJP's `thisLogger()` function, which is very handy!

2024-07-10 13:48 UTC, rock3r commented on int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/StandalonePainterHintsProvider.kt
> +                    .getInstance("JewelStandaloneShowcase")
Likely a copy-paste error

```suggestion
                    .getInstance(this::java.class)
```

Or also using the proposed `myLogger()`

2024-07-10 13:48 UTC, rock3r commented on int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/StandalonePainterHintsProvider.kt
> +                .getInstance("JewelStandaloneShowcase")
Ditto

2024-07-10 13:48 UTC, rock3r commented on int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/StandalonePainterHintsProvider.kt
> +                    .getInstance("JewelStandaloneShowcase")
Ditto

2024-07-10 13:48 UTC, rock3r commented on samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/ComponentShowcaseTab.kt
> +                    JewelLogger.getInstance("JewelIDEPluginShowcase").warn("Checked $it")
I'd use the composable's name for logging (although in real life you'd never log from the UI)

2024-07-10 13:48 UTC, rock3r commented on samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/dialog/JewelDemoAction.kt
> +                    .getInstance("JewelStandaloneShowcase")
```suggestion
                    .getInstance(this::class.java)
```

2024-07-10 13:48 UTC, rock3r commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/Main.kt
> +    JewelLogger.getInstance("JewelStandAloneShowcase").warn("Starting Jewel Standalone showcase app")
```suggestion
    JewelLogger.getInstance("JewelStandaloneShowcase").info("Starting Jewel Standalone showcase app")
```

We always style it as "standalone", one word. Also doesn't look like a warning

2024-07-10 13:48 UTC, rock3r commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/reflection/Views.kt
> +                    JewelLogger.getInstance("JewelStandaloneShowcase").error(e)
```suggestion
                    JewelLogger.getInstance("Views").error(e)
```

2024-07-10 13:48 UTC, rock3r commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/ChipsAndTree.kt
> +                                            .getInstance("JewelStandaloneShowcase")
```suggestion
                                            .getInstance("ChipsAndTree")
```

2024-07-10 13:48 UTC, rock3r commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/ChipsAndTree.kt
> +                                            .warn("Click on $index")
```suggestion
                                            .info("Click on $index")
```

2024-07-10 13:48 UTC, rock3r commented on samples/standalone/src/main/resources/logback.xml
> +<configuration>
Are we actually using Logback? I don't see its dependency

2024-07-10 13:48 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt
> +                .getInstance("JewelStandaloneShowcase")
```suggestion
                .getInstance(this::java.class)
```

In general I'd save the logger as a field, instead of creating an instance every time.

2024-07-10 13:48 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt
> +                .info("Cache hit for $basePath (accepted hints: ${scope.acceptedHints.joinToString()})")
This is a perfect candidate for `debug`

2024-07-10 13:48 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt
> +                        .getInstance("JewelStandaloneShowcase")
See above (and on the next line, too)

2024-07-10 13:48 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt
> +                        .info("Found resource: '$normalized'")
Ditto

2024-07-10 13:48 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt
> +                            .info("Loading icon $basePath(${scope.acceptedHints.joinToString()}) from $resourceUrl")
Ditto

2024-07-10 13:48 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt
> +                            .info("Patched SVG:\n\n$patchedSvg")
Debug :)

2024-07-10 13:48 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt
> +                            .getInstance("JewelStandaloneShowcase")
Same as before

2024-07-10 13:48 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt
> +                JewelLogger.getInstance("JewelStandaloneShowcase").error(message)
Ditto

2024-07-10 15:16 UTC, hamen commented on gradle/libs.versions.toml
> +poko = { id = "dev.drewhamilton.poko", version.ref = "poko" }
Definitely unintended. Actually, that made me think and I checked. This was disabled for some unknown reason:
![image](https://github.com/JetBrains/jewel/assets/19003/b713ef25-9e56-418b-9bea-50fc7849f6ea)

2024-07-10 15:17 UTC, hamen commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/util/JewelLogger.kt
> +public abstract class JewelLogger {
I wondered about `debug` tdh, but I didn't want to mess around too much, hoping that the original IntellJ one was doing the _right thing_. We can try to add them, if you want.

2024-07-10 15:18 UTC, hamen commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/util/JewelLogger.kt
> +        public fun getInstance(clazz: Class<*>): JewelLogger = getInstance('#'.toString() + clazz.name)
I like it. I'm adding it.

2024-07-10 15:36 UTC, rock3r commented on .idea/runConfigurations/IDE_sample.xml
> +    <log_file alias="IDE Logs" path="$PROJECT_DIR$/samples/ide-plugin/build/idea-sandbox/IC-2024.2/log/idea.log" show_all="true" />
Ah, no, you're right. It is now in a different folder. This will be fun in the future, we'll need to keep the run config up to date across branches -> major IJP versions.

2024-07-10 15:36 UTC, rock3r commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/util/JewelLogger.kt
> +public abstract class JewelLogger {
The IJ logger exposes debug and trace, and I'd expect to have them here as well

2024-07-11 10:59 UTC, hamen commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/reflection/Views.kt
> +                    JewelLogger.getInstance("JewelStandaloneShowcase").error(e)
Done in cf695bc236badd13f74ee83b170d5515cc2d327f

2024-07-11 11:00 UTC, hamen commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/ChipsAndTree.kt
> +                                            .getInstance("JewelStandaloneShowcase")
Done in 2cce3e9b1c23d978975125ae8da0ae9aea07e148

2024-07-11 11:01 UTC, hamen commented on samples/standalone/src/main/resources/logback.xml
> +<configuration>
Done in 8f53d07026c4f85148ea5b6873d49e8f4c8460c6

2024-07-11 12:45 UTC, rock3r requested changes
Looks like you've marked a lot of comments as resolved but then forgot to actually address them

2024-07-11 12:45 UTC, rock3r commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/util/JewelLogger.kt
> +public inline fun <reified T : Any> T.myLogger(category: String? = null): JewelLogger =
The point of this is that it uses the class to pick the category and not a string, please remove the parameter. The 'my' part of the API name makes no sense when your van override the category. People can use the existing API to get an instance with a custom category.

2024-07-11 12:45 UTC, rock3r commented on int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/StandalonePainterHintsProvider.kt
> +                JewelLogger
Please save loggers in fields, especially in hot paths like this that get invoked over and over

2024-07-11 12:45 UTC, rock3r commented on int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/StandalonePainterHintsProvider.kt
> +                    .getInstance("JewelStandaloneShowcase")
Not done yet

2024-07-11 12:45 UTC, rock3r commented on samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/ComponentShowcaseTab.kt
> +val logger = JewelLogger.getInstance("JewelPluginShowcase")
The name of the category has nothing to do with the composable it's used into

2024-07-11 12:45 UTC, rock3r commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/Main.kt
> +        .getInstance("JewelStandAloneShowcase")
Should be StandaloneSample, for consistency with how it's referred to everywhere else

2024-07-11 12:45 UTC, rock3r commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/Main.kt
> +        .info("Starting Jewel Standalone showcase app - on INFO")
Ditto, and please remove the last part as it's probably just a debugging leftover

2024-07-11 12:45 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt
> +                    JewelLogger
Use the field!

2024-07-11 12:45 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt
>          if (inDebugMode && cache[cacheKey] != null) {
Note: we should remove the debug flag since that's know handled by the logger

2024-07-11 12:45 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt
> +                            .getInstance("JewelStandaloneShowcase")
Still to fix, just use the field

2024-07-11 12:45 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt
> +                            .info("Patched SVG:\n\n$patchedSvg")
It's still not debug

2024-07-11 12:53 UTC, hamen commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt
>          if (inDebugMode && cache[cacheKey] != null) {
Done in 64daff4ef754c850300ffd1134bca9605b052ce5

2024-07-11 13:44 UTC, rock3r commented on samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/ComponentShowcaseTab.kt
> +    logger.warn("Welcome to JewelPluginShowcase")
There is no need to print this here. Sorry I had missed it before

2024-07-11 13:44 UTC, rock3r commented on samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/ComponentShowcaseTab.kt
> +                logger.debug("Clicked: $clicks1")
Please make all the click handlers print at the info level (or remove the logging entirely — after all, this is not a logger demo :) )

2024-07-11 13:44 UTC, rock3r commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/Main.kt
> +        .info("Starting Jewel Standalone showcase app")
One bit missing from before:

```suggestion
        .info("Starting Jewel Standalone sample")
```

Bigger picture though, same as for the one in the IDE sample, I don't really see the value of printing this here. I understand it was done for debugging while developing the logger, but... do we still need it?

2024-07-11 13:44 UTC, rock3r commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/ChipsAndTree.kt
> +                                            .warn("Click on $index")
Still not done

2024-07-11 13:53 UTC, hamen commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt
> +                            .info("Patched SVG:\n\n$patchedSvg")
I think there is something funny with GH. This is how it looks here:
![image](https://github.com/JetBrains/jewel/assets/19003/44720a6a-2bc2-4003-aa70-f5cb100a4d1e)

2024-07-11 14:02 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt
> +                            .info("Patched SVG:\n\n$patchedSvg")
Now it shows as debug lol ok GH

2024-07-11 14:03 UTC, rock3r approved these changes
:shipit:

2024-07-11 14:03 UTC, merged