Add scrollbars
JetBrains/jewel pull request #457
Opened 2024-07-18 15:22 UTC by hamen

2024-07-23 15:29 UTC, rock3r commented
Please add screenshots and videos of the scrollbars in action, and comparable Swing implementations, to help validate they look and behave as expected.

2024-07-23 16:12 UTC, rock3r requested changes
Please try to revert unneded code formatting changes, and split out both the standalone sample shortcuts (#462) and BTF2 introduction (#296) to keep this simple and self-contained.

2024-07-23 16:12 UTC, rock3r commented on samples/standalone/src/main/resources/icons/components/scroll.svg
> +</svg>
Please use the same size (16x16), colours (`#CED0D6` for dark, `#6C707E` for light), and style (stroke width 1, no round line caps) as the other icons.

2024-07-23 16:12 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/component/InputField.kt
> +
To keep this PR more legible, would it be possible to split the text area scrollbars work to a separate PR?

2024-07-23 16:12 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/component/InputField.kt
> +            )
Missing braces

2024-07-23 16:12 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/component/InputField.kt
> +    showScrollbar: Boolean = true,
Please no default values in internal functions, they can lead to mistakes like leaving `showScrollbar` on for `TextField` when it should be off — which concidentally I think is what has happened here 🤣

2024-07-23 16:12 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/component/TextArea.kt
> +public fun TextArea(
Can we deprecate the older ones? And possibly, provide a simple String-based TextArea that hides having to use the `TextFieldState`.

Also applies to `TextField` — it needs the same treatment we have for `TextArea`!

2024-07-29 10:45 UTC, hamen commented on decorated-window/src/main/kotlin/org/jetbrains/jewel/window/DecoratedWindow.kt
> +    state: WindowState =
I'll revert it, but the reason is that the original values make the windows tiny on my monitor, and I'm constantly resizing it to fit the content 🤣

2024-07-29 10:48 UTC, hamen commented on ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridge.kt
> +        retrieveIntAsDpOrUnspecified("CheckBox.iconSize").let {
I'm trying to understand what's causing the different formatting. Believe me, I'm dying by merge conflict every time I touch this file.

2024-07-29 10:51 UTC, rock3r commented on decorated-window/src/main/kotlin/org/jetbrains/jewel/window/DecoratedWindow.kt
> +    state: WindowState =
Ok, but keep the change locally in that case, don't commit it :)

2024-07-29 10:51 UTC, rock3r commented on ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridge.kt
> +        retrieveIntAsDpOrUnspecified("CheckBox.iconSize").let {
I feel you 🫂

2024-07-29 13:15 UTC, hamen commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/Main.kt
> +
Extracted in https://github.com/JetBrains/jewel/pull/502

2024-07-29 13:27 UTC, hamen commented on samples/standalone/src/main/resources/icons/components/scroll.svg
> +</svg>
👍🏻 also, this is a completely random picked icon. What's the icon pack we are usually referring to?

2024-07-29 13:47 UTC, rock3r commented on samples/standalone/src/main/resources/icons/components/scroll.svg
> +</svg>
I made all the other icons by hand, there is no icon pack :)

2024-07-29 14:19 UTC, rock3r commented on ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridge.kt
> +            trackPaddingExpanded = PaddingValues(horizontal = 0.dp),
```suggestion
            trackPadding = PaddingValues(),
            trackPaddingExpanded = PaddingValues(),
```

2024-07-30 16:25 UTC, rock3r commented on int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiScrollbarStyling.kt
> +    alwaysVisible: Boolean = true,
Please use Style and Behavior enums here; we have them, no reason to use booleans instead.

2024-07-30 16:27 UTC, rock3r commented on ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/ScrollbarBridge.kt
>  }
I would move these to the UI package and make them public. The scrollbars DO need to support all styles and behaviours (on macOS) both in standalone and bridge; the only thing we won't do — for now at least — is to port the logic to standalone to detect the current system setting. In standalone on macOS we always use `Overlay`/`JumpToSpot`

2024-07-31 11:18 UTC, hamen commented on ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/ScrollbarBridge.kt
>  }
Done in 9d1c8e2199e834f4d21d24e3380ca4ee2bc60ab4

2024-07-31 11:21 UTC, hamen commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/component/InputField.kt
> +            )
Done in 760b9c2af3c12aa0714784889ed2a327140a3a31

2024-08-01 16:31 UTC, hamen commented on samples/standalone/src/main/resources/icons/components/scroll.svg
> +</svg>
Done in https://github.com/JetBrains/jewel/pull/457/commits/273dcae9596f582e42b1bd5d5d0a197a406a87f3

2024-08-01 17:25 UTC, rock3r commented on int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiScrollbarStyling.kt
> +public fun ScrollbarStyle.Companion.winOsDark(
`windowsAndLinux*` here and below?

2024-08-01 17:28 UTC, rock3r commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Scrollbars.kt
> +        val resolvedStyle = readStyle()
Is this meant to be done to detect the initial style? I think the issue here is that this will be re-executed on every composition. You should probably call this "baseStyle", and remember(JewelTheme.isDark) it

2024-08-01 17:30 UTC, rock3r commented on int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiTabStyling.kt
> +        scrollbarStyle: ScrollbarStyle = ScrollbarStyle.macOsLight(),
This is most likely wrong — we need to at least pick between light and dark as needed, but tabs have different styling for scrollbars (thinner), and that should be addressed. Can be in a separate PR, but we need to make sure they look correct based on the OS, too.

2024-08-02 10:49 UTC, hamen commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Scrollbars.kt
> +        val resolvedStyle = readStyle()
Done in 9af3d55749056a6dde25b2c3316f00c3cf367597

2024-08-02 11:04 UTC, hamen commented on int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiTabStyling.kt
> +        scrollbarStyle: ScrollbarStyle = ScrollbarStyle.macOsLight(),
Nice catch. Thanks. Fixed in 8d01a88f5bb5305fe5492cc813a4f497d6df0316

For the Tab-specific style task, I opened an issue to keep track of it https://github.com/JetBrains/jewel/issues/511

2024-08-06 10:19 UTC, hamen commented on int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiScrollbarStyling.kt
> +public fun ScrollbarStyle.Companion.winOsDark(
Done in a37a1969e487fa4d552208ddd26e42ebeba2f2ed

2024-08-06 10:21 UTC, hamen commented on int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiScrollbarStyling.kt
> +
Done in 7e0f58dd6da132e6387e897ab2d2ec7b4f2cf2e1

2024-08-06 10:21 UTC, hamen commented on int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiScrollbarStyling.kt
> +
Done in 7e0f58dd6da132e6387e897ab2d2ec7b4f2cf2e1

2024-08-06 10:21 UTC, hamen commented on int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiScrollbarStyling.kt
> +// TAB STYLING
Done in 7e0f58dd6da132e6387e897ab2d2ec7b4f2cf2e1

2024-08-06 10:23 UTC, hamen commented on int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiScrollbarStyling.kt
> +public fun ScrollbarStyle.Companion.macOsTabLight(
Nice catch. It was indeed an unused duplicate method. Fixed in 137f7d7232390d7124f382f185f4a37f842307c0

2024-08-06 10:25 UTC, hamen commented on int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiScrollbarStyling.kt
> +public fun ScrollbarStyle.Companion.tabStripWinOsDark(
These are now `tabStripWindowsAndLinuxLight()` and `tabStripWindowsAndLinuxDark()` as for previous comment.

2024-08-06 10:29 UTC, hamen commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/TextFields.kt
> +            state = state4,
Done in 29285e23e49d82129fddb51ac95f3a737773ac3c

2024-08-06 10:30 UTC, hamen commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/TextFields.kt
> +            state = state5,
Done in 29285e23e49d82129fddb51ac95f3a737773ac3c

2024-08-06 10:30 UTC, hamen commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/TextFields.kt
> +            state = state,
Done in 29285e23e49d82129fddb51ac95f3a737773ac3c

2024-08-06 15:32 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Scrollbars.kt
> +                    style.colors.thumbBackgroundHovered
```suggestion
                    style.colors.thumbBackground
```

2024-08-06 15:32 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Scrollbars.kt
> +                style.colors.thumbBackgroundHovered
```suggestion
                style.colors.thumbBackground
```

2024-08-06 15:32 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/component/InputField.kt
> +    showScrollbar: Boolean,
```suggestion
    state: TextFieldState,
    enabled: Boolean,
    readOnly: Boolean,
    outline: Outline,
    undecorated: Boolean,
    keyboardOptions: KeyboardOptions,
    singleLine: Boolean,
    maxLines: Int,
    interactionSource: MutableInteractionSource,
    style: InputFieldStyle,
    textStyle: TextStyle,
    showScrollbar: Boolean,
    modifier: Modifier,
    decorationBox: @Composable (innerTextField: @Composable () -> Unit, state: InputFieldState) -> Unit,
```

2024-08-06 15:32 UTC, rock3r commented on .editorconfig
> +# noinspection EditorConfigKeyCorrectness
Please revert this file.

2024-08-06 15:32 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/component/TextField.kt
> +                .padding(style.metrics.contentPadding),
Please revert this.

2024-08-06 15:32 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/component/TextArea.kt
> +                .find { it.layoutId == PLACEHOLDER_ID }
Please revert this.

2024-08-06 15:32 UTC, rock3r commented on .idea/inspectionProfiles/Project_Default.xml
> -    <inspection_tool class="StructuralWrap" enabled="false" level="INFORMATION" enabled_by_default="false" />
Still TODO

2024-08-06 15:32 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/component/InputField.kt
>      onValueChange: (TextFieldValue) -> Unit,
Please revert this.

2024-08-06 15:32 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/component/InputField.kt
> +            .outline(inputState, outline, shape, Stroke.Alignment.Center),
Please revert this.

2024-08-06 15:32 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/component/InputField.kt
> +) : FocusableComponentState {
Please revert this.

2024-08-06 15:32 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/component/InputField.kt
> +                    (if (active) Active else 0UL),
Please revert this.

2024-08-06 15:32 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Scrollbars.kt
> +            }
Please revert this.

2024-08-06 15:32 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Scrollbars.kt
> +                                RoundedCornerShape(style.metrics.thumbCornerSize),
Please revert this.

2024-08-06 15:32 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/component/TextArea.kt
> +                .single { it.layoutId == TEXT_AREA_ID }
Please revert this.

2024-08-06 15:44 UTC, hamen commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Scrollbars.kt
> +                style.colors.thumbBackgroundHovered
Done in 70d2cda9

2024-08-06 15:47 UTC, hamen commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/component/InputField.kt
> +    showScrollbar: Boolean,
Done in e4943983

2024-08-07 10:51 UTC, closed without merging