New implementation by defaults and colors
JetBrains/jewel pull request #46
Opened 2023-06-01 19:16 UTC by devkanro

2023-06-05 08:12 UTC, rock3r requested changes
Great job! I have mostly minor comments. The only two changes I'd make are on the Button colours and the palettes.

2023-06-05 08:12 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/internal/Stroke.kt
> +            return "Stroke()"
Nit: I wouldn't override these `toString()`s since we're missing the actual type. I get that was the intent, but I don't think it's a good idea in this case

2023-06-05 08:12 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/internal/IntelliJColors.kt
> +    override fun toString(): String {
Do we need the override? It looks identical to the stock `toString()`

2023-06-05 08:12 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/internal/Stroke.kt
> +fun Stroke(width: Dp, brush: androidx.compose.ui.graphics.Brush, alignment: Stroke.Alignment): Stroke {
Import `Brush`

2023-06-05 08:12 UTC, rock3r commented on themes/int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/themes/intui/standalone/internal/Button.kt
> +            org.jetbrains.jewel.internal.buttonColors(
Import `buttonColors`

2023-06-05 08:12 UTC, rock3r commented on themes/int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/themes/intui/standalone/internal/Button.kt
> +        TODO("Not yet implemented")
Let's not forget to add it — although I am not sure what an outline button is. Is it a "normal" button, called "secondary" in the Int UI specs, whereas the `buttonColors()` above represent the "default" button, aka "primary"?

If that's the case, I would have the "primary" button be the special case, since there can only be one per screen, and the "secondary" button be the default for a button. This also reflects how they're implemented in Swing.

2023-06-05 08:12 UTC, rock3r commented on themes/int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/themes/intui/standalone/internal/DarkPalette.kt
> +class DarkPalette(
Here and in the `LightPalette`, instead of hardcoding the values, I'd instead refer to a colour palette with the same colour names you find in Figma and in the actual Swing themes. E.g., `IntUiColorPalette` that contains `Light` and `Dark`, and each have `Grey1` `Grey2`, etc etc

It's trivial to generate them from [`expUI_dark.theme.json`](https://github.com/JetBrains/intellij-community/blob/master/platform/platform-resources/src/themes/expUI/expUI_dark.theme.json) and [`expUI_light.theme.json`](https://github.com/JetBrains/intellij-community/blob/master/platform/platform-resources/src/themes/expUI/expUI_light.theme.json), and they keep these palettes much tidier, avoiding copy-paste errors and making it easier to then go and add more entries here.

2023-06-05 08:17 UTC, devkanro commented on core/src/main/kotlin/org/jetbrains/jewel/internal/Border.kt
> +package org.jetbrains.jewel.internal
Currently I just write the new implementation in this package so that @fscarponi can continue his work, after finishing most of the controls, I will migrate it out and replace the old controls

2023-06-05 08:20 UTC, devkanro commented on themes/int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/themes/intui/standalone/internal/Button.kt
> +        TODO("Not yet implemented")
OK, at present, I am referring to the code of material design, and theirs is to use the primary button as the default button. But I think what you said also makes sense.

2023-06-05 08:23 UTC, rock3r commented on themes/int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/themes/intui/standalone/internal/Button.kt
> +        TODO("Not yet implemented")
True, but I think this is something we should be coherent with the Darcula/IntUI implementation in Swing.

Material is a great source of inspiration in how to implement the theme when it comes to code structure and general patterns, and we should indeed follow that same approach; where it comes to higher level concepts though, we have more freedom. By choosing consistency with the Swing world we not only make it easier for folks to transition to Jewel, but also make our lives easier on the bridge side, as we don't have to think in reverse :)

2023-06-05 08:25 UTC, rock3r commented on themes/int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/themes/intui/standalone/internal/DarkPalette.kt
> +class DarkPalette(
To be clear, I don't think we should do it at runtime, but it should be trivially easy to parse that JSON and generate the corresponding Kotlin. For now, it can be done by hand in less than 1h. In the future we may want to automate it, but it's not necessary yet I reckon

2023-06-05 08:28 UTC, devkanro commented on core/src/main/kotlin/org/jetbrains/jewel/internal/Stroke.kt
> +            return "Stroke()"
These toString methods help us record these values in the modifier's `debugInspectorInfo`

2023-06-05 08:30 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/internal/Stroke.kt
> +            return "Stroke()"
Sure, but the `object`'s one would produce `None` — which is more useful than `Stroke()` as it contains the actual type and is less confusing — and the auto-generated ones for data classes would look identical, but also include the correct type instead of the generic `Stroke`.

2023-06-05 08:31 UTC, devkanro commented on themes/int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/themes/intui/standalone/internal/DarkPalette.kt
> +class DarkPalette(
OK, a gradle build script can do this

2023-06-05 08:34 UTC, devkanro commented on core/src/main/kotlin/org/jetbrains/jewel/internal/IntelliJColors.kt
> +    override fun toString(): String {
You are right, kotlin data class provides this implementation automatically, I would remove these unnecessary toString

2023-06-07 13:36 UTC, fscarponi approved these changes

2023-06-08 11:51 UTC, rock3r approved these changes
Sorry for the delay, been busy 😓

2023-06-08 11:51 UTC, merged