IntellijTree refactoring
JetBrains/jewel pull request #49
Opened 2023-06-12 12:56 UTC by fscarponi

@devkanro Can you take a look at this?

I'm moving the ijTree implementation to the new pattern.

2023-06-12 13:21 UTC, devkanro requested changes

2023-06-12 13:21 UTC, devkanro commented on themes/int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/themes/intui/standalone/internal/dark/DarkTheme.kt
> +import org.jetbrains.jewel.internal.*
Linters will be unhappy

2023-06-12 13:21 UTC, devkanro commented on core/src/main/kotlin/org/jetbrains/jewel/internal/IntellijTree.kt
> +    override fun nodeIconTint(): Color = nodeIconTintColor
Maybe we should unify the naming, iconColor or IconTint or IconTintColor

2023-06-12 13:48 UTC, fscarponi commented on core/src/main/kotlin/org/jetbrains/jewel/internal/IntellijTree.kt
> +    override fun nodeIconTint(): Color = nodeIconTintColor
*something*Color will be great!
so this will become nodeIconColor

2023-06-12 13:55 UTC, fscarponi commented on core/src/main/kotlin/org/jetbrains/jewel/internal/IntellijTree.kt
> +        selectionFocusedBackgroundColor = colors.elementBackgroundColor(isFocused = true, isSelected = true),
we need to reason about that a bit.

This is a TreeView<T> control, so you should provide the composable item lambda when you build the tree... maybe we can insert this color into the tree by default? it would be available when someone is composing the inner elements components

like
fun defaultItemForegroundColor : Color
fun defautlItembackgroundColor(isFocused, isSelected)  : Color

what do you think about that?

2023-06-12 14:05 UTC, devkanro commented on core/src/main/kotlin/org/jetbrains/jewel/internal/IntellijTree.kt
> +        selectionFocusedBackgroundColor = colors.elementBackgroundColor(isFocused = true, isSelected = true),
Yes, but you need to pay attention that the foreground color may also change depending on the state.

For example, in the darcula theme, the background color of focused item is set to a dark blue, so the foreground color is white at this time

And for list items, the isActive state may also affect the color, but we can put that aside until we implement the ActivableArea control.

2023-06-13 03:05 UTC, devkanro requested changes

2023-06-13 08:06 UTC, fscarponi commented on core/src/main/kotlin/org/jetbrains/jewel/internal/IntellijTree.kt
> +        selectionFocusedBackgroundColor = colors.elementBackgroundColor(isFocused = true, isSelected = true),
`
interface TreeColors {
    fun elementBackgroundColor(isFocused: Boolean, isSelected: Boolean): State<Color>
    fun elementForegroundColor(isFocused: Boolean, isSelected: Boolean): State<Color>

    fun nodeIconColor(): State<Color>
}
`

2023-06-13 09:32 UTC, devkanro approved these changes

2023-06-13 11:39 UTC, merged