Iterate on TextField and TextArea focused state UI
JetBrains/jewel pull request #540
Opened 2024-08-13 10:29 UTC by hamen

2024-08-14 11:40 UTC, rock3r commented
Looking at the screenshots, it looks like:
 * in standalone the corner radius is too large when focused (both text area and text field) — the value may be correct, but not the alignment of border + outline 
 * the text area paddings are wrong in this screenshot — is it outdated?
   ![](https://github.com/user-attachments/assets/1a75e43d-dd99-40e8-82dd-2c9c0d325653)


The screenshots of the buttons are not enough to compare and see if they're correct.

In general, in the future please don't title a PR as containing one fix when the PR fixes two separate and independent issues. I'd much rather have separate PRs for separate fixes, which obviates the problem.

2024-08-14 13:29 UTC, hamen commented
> Looking at the screenshots, it looks like:
> 
> * in standalone the corner radius is too large when focused (both text area and text field) — the value may be correct, but not the alignment of border + outline
I'll look into it.

> * the text area paddings are wrong in this screenshot — is it outdated?
Wrong paste. I have updated it.
![image](https://github.com/user-attachments/assets/75cded5d-2896-4346-a5a6-f7b9a72b3bad)

> 
> The screenshots of the buttons are not enough to compare and see if they're correct.
> 
> In general, in the future please don't title a PR as containing one fix when the PR fixes two separate and independent issues. I'd much rather have separate PRs for separate fixes, which obviates the problem.
I'll split the two PRs and provide more screenshots.

2024-08-19 07:35 UTC, rock3r requested changes

2024-08-19 07:35 UTC, rock3r commented on .idea/detekt.xml
> +    <option name="treatAsErrors" value="true" />
Please revert this — we're not shipping that jar

2024-08-19 07:35 UTC, rock3r commented on ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridge.kt
> +                cornerSize = retrieveArcAsCornerSize("Component.arc"),
This is exactly the same thing, it just used a type-safe API instead of the string-based one

2024-08-19 07:35 UTC, rock3r commented on ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridge.kt
> +                contentPadding = PaddingValues(horizontal = 8.dp, vertical = 0.dp),
You can omit the `0.dp` parameter:

```suggestion
                contentPadding = PaddingValues(horizontal = 8.dp),
```

2024-08-19 07:35 UTC, rock3r commented on int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiTextAreaStyling.kt
> +    focusOutlineExpand: Dp = 1.dp,
This is different than in the bridge (where it's `2.dp`), smells like either of those is wrong. Hardcoded values should not be different between Standalone and Bridge, since the drawing logic is the same!

2024-08-19 07:35 UTC, rock3r commented on samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/SwingComparisonTabPanel.kt
> +                    modifier = Modifier.background(Color.Green).padding(4.dp),
Is this supposed to be green? Looks like a debug thing

2024-08-19 07:35 UTC, rock3r commented on samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/SwingComparisonTabPanel.kt
> +                    val state1 = rememberTextFieldState("")
Not a fan of all three textfields sharing a single state

2024-08-19 07:35 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/component/InputField.kt
> +                (if (enabled) Enabled else 0UL) or
Please revert

2024-08-19 07:35 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/component/InputField.kt
> +        modifier
Please revert

2024-08-19 07:35 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt
> +            //logger.debug("Cache hit for $basePath (accepted hints: ${scope.acceptedHints.joinToString()})")
Please revert

2024-08-19 07:35 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt
> +                //logger.debug("Cache miss for $basePath (accepted hints: ${scope.acceptedHints.joinToString()})")
Please revert

2024-08-19 07:35 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt
> +                //logger.debug("Found resource: '$normalized'")
Please revert

2024-08-19 07:35 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt
> +                    //logger.debug("Loading icon $basePath(${scope.acceptedHints.joinToString()}) from $resourceUrl")
Please revert

2024-08-19 07:35 UTC, rock3r commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt
> +                //.also { patchedSvg -> logger.debug("Patched SVG:\n\n$patchedSvg") }
Please revert

2024-08-19 08:54 UTC, hamen commented on .idea/detekt.xml
> +    <option name="treatAsErrors" value="true" />
Done in d5c71392. I'll try to ignore the changes locally 👍🏻

2024-08-19 08:55 UTC, hamen commented on ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridge.kt
> +                cornerSize = retrieveArcAsCornerSize("Component.arc"),
Other methods use that. I changed it for consistency.

2024-08-19 08:56 UTC, hamen commented on ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridge.kt
> +                contentPadding = PaddingValues(horizontal = 8.dp, vertical = 0.dp),
Done in 26c91bf7

2024-08-19 11:39 UTC, hamen commented on ui/src/main/kotlin/org/jetbrains/jewel/ui/component/InputField.kt
> +        modifier
They slip through the formatter. So annoying.

2024-08-19 17:21 UTC, rock3r commented on int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiTextFieldStyling.kt
> +    minSize: DpSize = DpSize(49.dp, 28.dp),
This new min size seems tiny... Where does the new value come from?

2024-08-19 17:21 UTC, rock3r commented on samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/SwingComparisonTabPanel.kt
> +                    modifier = Modifier.width(198.dp),
Rather than hardcoding the size to match the default, maybe we should make the default take the same size as Swing's default

2024-08-19 17:21 UTC, rock3r commented
Conflicts to solve here, too

2024-08-20 08:38 UTC, hamen commented on int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiTextFieldStyling.kt
> +    minSize: DpSize = DpSize(49.dp, 28.dp),
`49.dp` feels super arbitrary so _I assume_, or should I say I hope, I got it from Swing. I'll track it down and add a reference or worst case scenario I'll revert it.

2024-08-21 08:23 UTC, hamen commented on samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/SwingComparisonTabPanel.kt
> +                    modifier = Modifier.width(198.dp),
According to the inspector, the Swing one is not running at minimum size:
![image](https://github.com/user-attachments/assets/1f5b5dc0-89c6-4559-83af-d0631b0dab9e)

Running the Compose one at minimum size (obtained with `JBUI.CurrentTheme.TextField.minimumSize().toDpSize()`) gives us this:
![image](https://github.com/user-attachments/assets/ce01b4d2-6e9a-47e8-8c9c-1d7be6cc3719)

It's the infamous `49.dp` that we have replaced with the magic `144.dp`.
WDYT?

2024-08-21 08:40 UTC, hamen commented on int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiTextFieldStyling.kt
> +    minSize: DpSize = DpSize(49.dp, 28.dp),
I'm reverting this because `144.dp` seems to make more sense tbh.

2024-08-21 08:57 UTC, rock3r commented on samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/SwingComparisonTabPanel.kt
> +                    modifier = Modifier.width(198.dp),
As I have told you twice yesterday you CANNOT judge component sizes from Kotlin DSL surfaces (such as this one, as again I called out yesterday) because the components here have a forced size set by the DSL layout

2024-08-26 15:46 UTC, rock3r approved these changes

2024-08-26 15:52 UTC, merged