Migrate TitleBarView to new Icon API
JetBrains/jewel pull request #546
Opened 2024-08-16 09:47 UTC by hamen

This PR improves consistency and removes a few warnings.

2024-08-18 08:03 UTC, devkanro approved these changes

2024-08-19 07:19 UTC, rock3r commented
Do they still look right even without the size hints? This is not a lossless change, the way you implemented it

2024-08-19 08:24 UTC, rock3r requested changes

2024-08-19 08:24 UTC, rock3r commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/StandaloneSampleIcons.kt
> +    val themeDark20 = PathIconKey("icons/darkTheme@20x20.svg", StandaloneSampleIcons::class.java)
No, this is not correct. You need to use the `Size` `PainterHint`.

2024-08-19 08:24 UTC, hamen commented
Thank you for the feedback. I changed the approach. I used a different overload and added the same icons as before. I think they look the same now.

2024-08-19 08:25 UTC, rock3r commented
The new approach is incorrect, you should _never_ have to create additional keys. Use `PainterHints` instead, they're there for this purpose.

2024-08-19 08:25 UTC, hamen commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/StandaloneSampleIcons.kt
> +    val themeDark20 = PathIconKey("icons/darkTheme@20x20.svg", StandaloneSampleIcons::class.java)
OK. I'll check the method.

2024-08-19 08:41 UTC, hamen commented
I added the `PainterHint` and removed the unnecessary icon declaration. I also removed the `20x20` SVG files.
Considering that I took me a moment to figure out how to use the `Size` `PainterHint`, would it be useful to point the user to this example in the `README`?

2024-08-19 08:52 UTC, rock3r commented
Why did you remove the svg files? They were there for a reason...

As for the `Size` `PainterHint` in the readme, isn't there any mention of `PainterHint`s in the readme already? If there is, I don't think we should specifically add `Size`, since it's a hint like all others. If there is no mention at all of PainterHint

2024-08-19 08:53 UTC, rock3r commented
Sorry for closing, I mis-clicked

2024-08-19 09:04 UTC, hamen commented
I restored the icons in 0f812a21. I thought we would use the new approach from now on.

2024-08-19 09:06 UTC, hamen commented
> As for the `Size` `PainterHint` in the readme, isn't there any mention of `PainterHint`s in the readme already?

We mention it in https://github.com/JetBrains/jewel?tab=readme-ov-file#icon-runtime-patching, but the size example popped out from a test. It's just me having little knowledge about this topic and thinking about other people not familiar with this stuff.

2024-08-19 13:34 UTC, rock3r commented
>We mention it in https://github.com/JetBrains/jewel?tab=readme-ov-file#icon-runtime-patching, but the size example popped out from a test. It's just me having little knowledge about this topic and thinking about other people not familiar with this stuff.

I think the vague mention we have is ok for now, because if we start documenting one `PainterHint` we need to document _all_ of them, and that's not a priority right now

2024-08-19 17:15 UTC, rock3r commented
This has conflicts that need fixing with main.

And, re:

>I restored the icons in https://github.com/JetBrains/jewel/commit/0f812a2181fe9cdc236eb351c054c3dd895b1805. I thought we would use the new approach from now on.

We _are_ using the new approach. The Size painter hint looks for an image with the right size in its file name, and if there isn't one, just stretches the "base" one.

2024-08-19 17:16 UTC, rock3r commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/TitleBarView.kt
> +                                iconClass = StandaloneSampleIcons::class.java,
Here and below, you don't need to specify the iconClass anymore, the keys have one embedded that's used by default.

2024-08-20 09:11 UTC, rock3r commented
That's how the icon loading works in the IJP in general; it is _somewhat_ [documented](https://plugins.jetbrains.com/docs/intellij/icons.html#png-format-deprecated) — however, as usual, not very well.

2024-08-20 09:12 UTC, rock3r approved these changes

2024-08-20 09:12 UTC, merged