Add Pointer Release Handler to PointerEventActions
JetBrains/jewel pull request #626
Opened 2024-10-10 14:17 UTC by abarrafo

Supporting more granular control for consumers by exposing a `handlePointerEventRelease`

Includes example demonstrating Customized `DefaultTreeViewPointerEventAction` modifying long-press vs short-press, and, right click behavior.  Model use case: When you want to use context menu actions with many selectedElement(s). Or, when you want to support click, hold and drag-n-drop actions with selectedElement(s) without reseting the selection state.

2024-10-10 14:18 UTC, abarrafo commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/CustomLazyTree.kt
> +// selection here for both primary button presses, and long press (drag) use-cases
```suggestion
// selection behavior here for both right button presses, and long press (drag) use-cases
```

2024-10-14 12:31 UTC, rock3r requested changes

2024-10-14 12:31 UTC, rock3r commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/ChipsAndTree.kt
> +            onElementDoubleClick = {},
These don't really seem too useful since they don't demonstrate much. Maybe add listeners on the existing tree sample, to show a menu or something?

2024-10-14 12:31 UTC, rock3r commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/CustomLazyTree.kt
> +// selection here for both primary button presses, and long press (drag) use-cases
You need to make the changes to your branch if you want to tweak the comment :)

2024-10-14 12:31 UTC, rock3r commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/CustomLazyTree.kt
> +fun <T> CustomLazyTree(
I don't think this is super valuable as-is. I get what you're trying to do, but I have some concerns about the way it is implemented here.

This adds extremely little to the existing LazyColumn APIs, and if it were that important to have a `SimplePointerEventActions` class, then it should live alongside the `SelectableLazyColumn`, and potentially be used in a `SelectableLazyColumn` and `LazyTree` overload, not be in a sample.

2024-10-14 13:46 UTC, abarrafo commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/CustomLazyTree.kt
> +fun <T> CustomLazyTree(
Yup,  I figured. The change I really want  in is, `public fun handlePointerEventRelease()` on the PointerEventActions and subsequent call on the BasicLazyTreeColumn.  Allowing for us to handle `List<Elements>` in the tree with more granularity depending on the pointer events. 

Agreed this really does not add much outside of a very simple sample (demonstrating right click, and long click selection behavior overrides in comparison to the default). Maybe we update the Lazy tree to simply take a `PointerEventActions`, that would simplify things a bit for us users downstream wanting to handle those events.   

I'm not sure a sample is even value add, to be honest.

2024-10-14 15:55 UTC, rock3r commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/CustomLazyTree.kt
> +fun <T> CustomLazyTree(
I'll leave it to @fscarponi to decide on the Tree API, I have nothing against surfacing the PointerEventActions there.

2024-10-14 19:12 UTC, fscarponi commented
Hi Folks,

Something seems off. I need to dive into this topic a bit more deeply.
I'm currently swamped with work, so I'll need a bit of time to look into this. I should be able to take a first look tomorrow and hopefully provide you with some feedback then. Be patient!

2024-10-14 19:24 UTC, fscarponi commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/CustomLazyTree.kt
> +fun <T> CustomLazyTree(
see [here](https://github.com/JetBrains/jewel/pull/626#issuecomment-2412031527)

2024-10-15 11:09 UTC, abarrafo commented
Here is a quick demo of the current behavior, although @fscarponi  already gave me a path for handling right clicks, i just have not implemented that yet on my file explorer. 

Essentially, the issue is we lose selected items on click and drag actions... Which the above pointer action addition would give me a path to address. 


https://github.com/user-attachments/assets/740f14d9-8b89-4158-ad51-b84cb445097e

2024-10-16 07:22 UTC, fscarponi commented
> Here is a quick demo of the current behavior, although @fscarponi already gave me a path for handling right clicks, i just have not implemented that yet on my file explorer.
> 
> Essentially, the issue is we lose selected items on click and drag actions... Which the above pointer action addition would give me a path to address.
> 
>  Screencast.from.2024-10-15.13-05-37.mp4

i'm investigating right now, thanks, the use case video will help me!

2024-10-16 08:15 UTC, fscarponi commented
Hi @abarrafo , Tanks for the patience! what if we consider handling this logic where all pointerEvents are handled?
I've not finished yet to cover this use case, but this is the idea:
```

public class DragTreeViewPointerEventAction(
    val treeState: TreeState,
    val onMoveElement: (Set<*>) -> Unit,
) : DefaultSelectableLazyColumnEventAction() {
    override fun handlePointerEventPress(
        pointerEvent: PointerEvent,
        keybindings: SelectableColumnKeybindings,
        selectableLazyListState: SelectableLazyListState,
        selectionMode: SelectionMode,
        allKeys: List<SelectableLazyListKey>,
        key: Any,
    ) {
        with(keybindings) {
            when {
                pointerEvent.keyboardModifiers.isContiguousSelectionKeyPressed &&
                    pointerEvent.keyboardModifiers.isCtrlPressed -> {
                }

                pointerEvent.keyboardModifiers.isContiguousSelectionKeyPressed -> {
                    super.onExtendSelectionToKey(key, allKeys, selectableLazyListState, selectionMode)
                }

                pointerEvent.keyboardModifiers.isMultiSelectionKeyPressed -> {
                    selectableLazyListState.lastKeyEventUsedMouse = false
                    super.toggleKeySelection(key, allKeys, selectableLazyListState, selectionMode)
                }

                else -> {

                    //drag and drop have sense only if u act on an already selected element
                    if (key !in selectableLazyListState.selectedKeys) {

                        selectableLazyListState.selectedKeys = setOf(key)

                    } else {

                        when (val eventType = pointerEvent.type) {

                            PointerEventType.Unknown, PointerEventType.Enter , PointerEventType.Move -> {
                                //not needed
                            }

                            PointerEventType.Press -> {
                                val pointerButton=pointerEvent.button ?: return@with
                                when {
                                    pointerButton.isPrimary ->{
                                        //do nothing this can be a drag n drop
                                    }
                                    pointerButton.isSecondary ->{
                                        //handle secondary click logic
                                    }
                                    else->{
                                        //go deep if u needs
                                    }
                                }
                            }
                            PointerEventType.Release ->{ //change the selection on release
                                selectableLazyListState.selectedKeys = setOf(key) //change the selection
                            }
                            PointerEventType.Exit ->{
                                //is a mouse button pressed? are u leaving the area? this is a drag and drop
                                if(primaryButtonIsDown()) onMoveElement(treeState.selectedKeys)
                            }
                            

                        }
                    }
                }
            }
        }
    }
}
```

2024-10-16 08:26 UTC, abarrafo commented
That should work.

2024-10-16 08:30 UTC, abarrafo commented
I think we want extend from DefaultTreeViewPointerEventAction instead? But otherwise I believe this will work.

2024-10-16 09:04 UTC, abarrafo commented
Yes, confirmed, this works. :bow:  

We can close this.


https://github.com/user-attachments/assets/b186c8da-3292-479d-b6d7-d144b53c598d

2024-10-16 10:45 UTC, fscarponi commented
@abarrafo We will be glad if you take time to write a small example for standalone

2024-10-16 10:45 UTC, closed without merging