ProrgessBar Implementation
JetBrains/jewel pull request #69
Opened 2023-06-21 14:44 UTC by fscarponi

https://github.com/JetBrains/jewel/assets/36624359/331e5edb-d51d-47e4-9b38-0c192167c081

2023-06-21 15:56 UTC, devkanro approved these changes

2023-06-21 15:56 UTC, devkanro commented
Nicely done

2023-06-21 15:56 UTC, merged

2023-06-21 15:57 UTC, rock3r commented
I was reviewing this :( @fscarponi please address the comments in a separate PR

2023-06-21 15:58 UTC, rock3r requested changes

2023-06-21 15:58 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/LinearProgressBar.kt
> +        animationSpec = tween(durationMillis = 250, easing = LinearEasing)
I would not use a Linear easing in this case, but rather leave the default, as it looks much better when you have actual easing in/out (for the indeterminate case, it's right to use linear because we want the velocity to be constant)

2023-06-21 15:58 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/LinearProgressBar.kt
> +    colors: ProgressBarColors = defaults.colors()
If you're already passing in the defaults, you shouldn't need to also pass in the colours. I'd remove this from all composables.

2023-06-21 15:58 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/LinearProgressBar.kt
> +            .drawWithContent {
This is pretty cheap, but in general, we could consider drawWithCache in more complex scenarios (or when we do perf optimisations)

2023-06-21 15:58 UTC, rock3r commented on samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/JewelDemoToolWindow.kt
> +                        // TODO progressbar compose
You're missing the Compose one here :)

2023-06-21 15:58 UTC, rock3r commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/Main.kt
>                  // take this at the end, because it's a bit taller
We should remove this comment now that it's attached to nothing

2023-06-21 15:58 UTC, rock3r commented on themes/int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/themes/intui/standalone/light/LightProgressBarDefaults.kt
> +@file:Suppress("MagicNumber")
We should really suppress that Detekt rule... I always forget

2023-06-22 07:02 UTC, fscarponi commented on core/src/main/kotlin/org/jetbrains/jewel/LinearProgressBar.kt
> +    colors: ProgressBarColors = defaults.colors()
Sorry but i'm not convinced that removing it is the best option. I understand that seems to be redundant, but in your idea, we will sacrifice usability for good looking api.

Let's watch a common scenario: a user/dev is creating his plugin, and he wants just one different color for the progress bar (for a specific purpose not related to an ide loading operation)
Those are the 2 patterns in comparison, the first does not expose colors parameter, the second one does
<img width="1122" alt="image" src="https://github.com/JetBrains/jewel/assets/36624359/c06a8985-7645-4917-b602-157481cbab28">

2023-06-22 07:05 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/LinearProgressBar.kt
> +    colors: ProgressBarColors = defaults.colors()
Is there a specific reason why the defaults aren't a data class? I also agree you shouldn't have to implement a bloody object. But in an ideal scenario, you'd only need to do `ProgressBarDefaults(colours = ...)`, or `whateverDefaultsFromTheTheme.copy(colours = ...)`

2023-06-22 07:07 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/LinearProgressBar.kt
> +    colors: ProgressBarColors = defaults.colors()
This is to say, the problem to me seems that the defaults are implemented with an hostile pattern, and exposing the colours is a patch for the symptom rather than a fix for the problem

2023-06-22 07:19 UTC, fscarponi commented on samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/JewelDemoToolWindow.kt
> +                        // TODO progressbar compose
something is broken in this file, there is no way to let the ide start the analysis, so it is like coding with eyes closed. i will just put the invocation there for now

2023-06-22 07:21 UTC, rock3r commented on samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/JewelDemoToolWindow.kt
> +                        // TODO progressbar compose
It happens sometimes and it's super annoying! Usually invalidating caches helps for me

2023-06-22 09:43 UTC, fscarponi commented on core/src/main/kotlin/org/jetbrains/jewel/LinearProgressBar.kt
> +    colors: ProgressBarColors = defaults.colors()
defaults are functions that usually take a state as a parameter.

ex
fun backGroudColor(state: ComponentState)

when ComponentState is dataclass like this

data class ComponentState(
val isFocused,
val isSelected,
val isHovered...)

so in the background function, you can simply run a when on the state....

2023-06-22 09:45 UTC, fscarponi commented on samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/JewelDemoToolWindow.kt
> +                        // TODO progressbar compose
it probably is something else, when i cancel the cache, it starts analyzing, and an exception is thrown by the IDE...

2023-06-22 10:24 UTC, rock3r commented on samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/JewelDemoToolWindow.kt
> +                        // TODO progressbar compose
Sigh :(

2023-06-22 10:25 UTC, rock3r commented on themes/int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/themes/intui/standalone/light/LightProgressBarDefaults.kt
> +@file:Suppress("MagicNumber")
Filed in #72