Fixes on Tree Chip and TextColor Handling, impl for Tabs and TabStrip
JetBrains/jewel pull request #90
Opened 2023-07-31 12:25 UTC by fscarponi

```kotlin
TabStrip(Modifier.fillMaxWidth()) {
            tab(
                tabNameString = "Tab 1",
                closable = false,
                selected = selectedTab == 0,
                tabIconResource = "icons/kotlin.svg",
                onTabClick = { selectedTab = 0 }
            )
            tabs(
                10,
                selected = { selectedTab == it + 1 },
                closable = false,
                tabNameString = { "tab " + (it + 1) },
                tabIconResource = { "icons/kotlin.svg" },
                onTabClick = { selectedTab = it + 1 },
                onTabClose = { },
                styleType = { if (it) TabStyleType.Default else TabStyleType.Editor }
            )
           editorTab(
                tabNameString = "Tab 1",
                closable = false,
                selected = selectedTab == 0,
                tabIconResource = "icons/kotlin.svg",
                onTabClick = { selectedTab = 0 }
            )
            ditorTabs(
                10,
                selected = { selectedTab == it + 1 },
                closable = false,
                tabNameString = { "tab " + (it + 1) },
                tabIconResource = { "icons/kotlin.svg" },
                onTabClick = { selectedTab = it + 1 },
                onTabClose = { },
                styleType = { if (it) TabStyleType.Default else TabStyleType.Editor }
            )
        }
```

2023-07-31 14:32 UTC, rock3r requested changes

2023-07-31 14:32 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/TabStrip.kt
> +}
I'd recommend a simpler approach, like the one done by lazy lists: create an internal/private `TabStripScopeImpl` class that implements `TabStripScope` and stores the items added in a private backing mutable list. You could even use the same `[Mutable]IntervalList<T>` APIs that the lazy lists use, but you don't necessarily need to. A simple mutable list would work fine.

2023-07-31 14:32 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/Tabs.kt
> +internal fun TabImpl(
Should be private

2023-07-31 14:32 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/Tabs.kt
> +    remember(selected) { tabState = tabState.copy(selected = selected) }
This looks extra dodgy — why do we need remember on something that isn't used anywhere? Should this be an effect? But even then, this seems to be doing what the previous line is doing anyway

2023-07-31 14:32 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/Tabs.kt
> +    val lineThickness = remember { tabStyle.metrics.underlineThickness }
Why is this remembered? It's not a state. It only affects drawing as well. I have a vague recollection of this being a workaround for something but I don't remember what :)

2023-07-31 14:32 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/styling/TabStyling.kt
> +    fun backGroundColorFor(state: TabState) = rememberUpdatedState(
It's `background`, not `backGround`

2023-07-31 14:32 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/styling/LazyTreeStyling.kt
> +    val elementForeground: Color
We use `content`, not `foreground`

2023-07-31 14:32 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/Tabs.kt
> +            }
You should use `LaunchedEffect(interactionSource) { ... }` to update the state! This is wrong (and expensive). See how other components do this.

2023-07-31 14:32 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/Tabs.kt
> +                val capDxFix = 3f
Not sure what this magic number is for... Seems fishy we can take arbitrary thicknesses but this is hardcoded

2023-07-31 14:32 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/styling/TabStyling.kt
> +interface TabMetrics {
Missing `@Stable`/`@Immutable`

2023-07-31 14:32 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/styling/TabStyling.kt
> +interface TabColors {
Missing `@Stable`/`@Immutable`

2023-07-31 14:32 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/styling/TabStyling.kt
> +value class TabState(val state: ULong) {
This is not tracking a number of actual valid states — see comments above re: this being a `SelectableComponentState`

2023-07-31 14:32 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/styling/TabStyling.kt
> +    val closeSelectedTint: Color
This is wrong — you shouldn't be tinting the icon. There are different icons for different states:

<img width="269" alt="image" src="https://github.com/JetBrains/jewel/assets/153802/80b2f6c7-41b1-49fb-9c46-d8e94991e9e4">

2023-07-31 14:32 UTC, rock3r commented on samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/components/Tabs.kt
> +//    }
Can we delete this if it's unused?

2023-07-31 14:32 UTC, rock3r commented on samples/standalone/src/main/resources/icons/kotlin.svg
Nit: we should likely be using the [current logo](https://kotlinlang.org/docs/kotlin-brand-assets.html#kotlin-logo), not the old one

2023-08-02 13:57 UTC, rock3r requested changes

2023-08-02 13:57 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/Dropdown.kt
> +            dropdownState = dropdownState.copy(enabled = enabled, outline = Outline.Error)
Added #91 to track that we need to move the outline out of the component state

2023-08-02 13:57 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/Menu.kt
>      override fun toString() =
Need to update this too

2023-08-02 13:57 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/TabStrip.kt
> +        Modifier
This modifier should be applied to the `Row`, and the `Box` removed as unnecessary

2023-08-02 13:57 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/TabStrip.kt
> +                .fillMaxWidth()
Don't do this — respect the size set by the `modifier` passed in.

2023-08-02 13:57 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/Tabs.kt
> +    }
These should live in the scope where the component they refer to is — in the `if (showCloseIcon)` block.

2023-08-02 13:57 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/Tabs.kt
> +                    Box(Modifier.size(16.dp)) {}
You could use a `Spacer(Modifier.size(16.dp))` instead, since you have no content.

2023-08-02 13:57 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/Tabs.kt
> +value class TabCloseButtonState(val state: ULong) : InteractiveComponentState {
You could literally just use a `ButtonState` instead of creating a new, identical, one

2023-08-02 14:03 UTC, fscarponi commented on core/src/main/kotlin/org/jetbrains/jewel/TabStrip.kt
> +                    enabled = isHovered,
This is the behavior of Editor TabStrip in the IDE, can explain how to reproduce a different behavior?

2023-08-02 14:05 UTC, fscarponi commented on core/src/main/kotlin/org/jetbrains/jewel/TabStrip.kt
> +                    state = scrollState,
This is the behavior of Editor TabStrip in the IDE if you are over the tabStrip in the editor Tab Strip, vertical scroll will produce a horizontal scroll.

2023-08-02 14:13 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/TabStrip.kt
> +                    enabled = isHovered,
I'm sorry but I don't follow — I don't know how I would repro this behaviour you're talking about to begin with. That's why I am saying this seems wrong. I don't understand why the tab strip should not be scrollable unless it's hovered.

The reason I don't understand is that scroll only works when you hover the scrollable component with the pointer (the children are not focusable, so you can't even use the keyboard to scroll). Or am I mistaken?

2023-08-02 14:13 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/TabStrip.kt
> +                .horizontalScroll(scrollState)
See [previous comment](https://github.com/JetBrains/jewel/pull/90#discussion_r1281969099)

2023-08-02 14:14 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/TabStrip.kt
> +                    state = scrollState,
I don't think your answer is in any way related to my comment

2023-08-02 14:23 UTC, fscarponi commented on core/src/main/kotlin/org/jetbrains/jewel/Tabs.kt
> +            }
outdate, already done

2023-08-02 14:26 UTC, fscarponi commented on core/src/main/kotlin/org/jetbrains/jewel/Tabs.kt
> +                val capDxFix = 3f
[we already discussed about that] (https://github.com/JetBrains/jewel/issues/79)

2023-08-02 14:29 UTC, fscarponi commented on core/src/main/kotlin/org/jetbrains/jewel/styling/TabStyling.kt
> +interface TabMetrics {
outdated, already soved

2023-08-02 14:31 UTC, fscarponi commented on core/src/main/kotlin/org/jetbrains/jewel/styling/LazyTreeStyling.kt
> +    fun elementForegroundFor(state: TreeElementState) = rememberUpdatedState(
outdated

2023-08-02 14:32 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/Tabs.kt
> +                val capDxFix = 3f
I know _why_ there are rounded caps and I know you have to make the line stay inside the actual tab. That is not what I pointed out. What I pointed out is that 3f is a hardcoded value that will only work when the line is exactly 6 dp wide. The cap "extra bit" is always strokeWidth / 2 wide, so hardcoding it to 3 is wrong.

Not only that, this will probably only work for a specific density value, since it's not scaled based on the density, whereas the other values are (see line 111 converting a dp value to pixels, which is a density-aware operation).

2023-08-02 14:33 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/styling/LazyTreeStyling.kt
> +    fun elementForegroundFor(state: TreeElementState) = rememberUpdatedState(
You know you can just mark things as resolved once you address them, right?

2023-08-02 14:44 UTC, fscarponi commented on core/src/main/kotlin/org/jetbrains/jewel/TabStrip.kt
> +        Modifier
doing this, the horizontal scroll bar stop working.

2023-08-02 14:52 UTC, fscarponi commented on foundation/src/main/kotlin/org/jetbrains/jewel/foundation/tree/BasicLazyTree.kt
>          private val Focused = 1UL shl 0
tree should be reimplemented, it will be done in a future pr

2023-08-02 14:59 UTC, fscarponi commented on core/src/main/kotlin/org/jetbrains/jewel/styling/ResourcePainterProvider.kt
> +                state is SelectableComponentState && state.isFocused -> append("Focused")
ups!

2023-08-02 15:08 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/TabStrip.kt
> +            modifier = modifier
FYI, the `modifier` parameter should only ever be applied to the _one_ composable that sits at the root level — see https://github.com/androidx/androidx/blob/androidx-main/compose/docs/compose-component-api-guidelines.md#modifier-parameter

2023-08-02 15:08 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/TabStrip.kt
> +        Modifier
That is because you are using the scrollbars wrong — you should only have one top-level `Box` that contains the `Row` and the `HorizontalScrollbar` (see [the Compose Desktop docs](https://github.com/JetBrains/compose-multiplatform/tree/master/tutorials/Desktop_Components#scrollbars) for an example).

If you simplify your setup to look like the sample, it should work fine.

2023-08-03 07:47 UTC, fscarponi commented on core/src/main/kotlin/org/jetbrains/jewel/TabStrip.kt
> +        Modifier
Ok, after a deep reading of the example, simplifying the code to match the perfect use case of example
```
box{
    box{
      ROW{}
    }
    if (should) HorizontalScroller
}
```
it did not solve the problem because the focus handling does not work as well as it should
( tried also to move the focus(interactionSource) in each container )

2023-08-03 08:10 UTC, fscarponi commented on core/src/main/kotlin/org/jetbrains/jewel/TabStrip.kt
> +            modifier = modifier
the mistake was done...

2023-08-03 08:12 UTC, fscarponi commented on core/src/main/kotlin/org/jetbrains/jewel/TabStrip.kt
> +        Modifier
ok there was a problem with InteractionSource, using a coroutine to handle the hover event, solved the problem.

2023-08-03 10:30 UTC, fscarponi commented on core/src/main/kotlin/org/jetbrains/jewel/TabStrip.kt
> +                .fillMaxWidth()
but correct if i'm wrong… the top Box respects the size sets by the modifier passed in... the inside row will fit the box size...

2023-08-03 10:33 UTC, fscarponi commented on core/src/main/kotlin/org/jetbrains/jewel/TabStrip.kt
> +                    .matchParentSize()
already solved

2023-08-03 11:04 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/TabStrip.kt
> +            modifier = modifier
I don't understand what you mean 😅

2023-08-03 11:13 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/TabStrip.kt
> +                .fillMaxWidth()
The code looked different when I wrote this, but regardless, if the `modifier` passed in doesn't set a specific width, this will make the `Row` take up all available width, which in turn will make the `Box` do the same. What is the reason you have this modifier? What are you trying to achieve, that doesn't work if the `Row` is just allowed to take up as much space as it needs (up to the point where it makes the parent take the maximum width), which is the default behaviour?

2023-08-03 11:13 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/TabStrip.kt
> +                    state = scrollState,
Ping on this

2023-08-03 11:13 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/TabStrip.kt
> +                    enabled = isHovered,
I think you're missing my point:

>[by default] scroll only works when you hover the scrollable component with the pointer

Given that scroll does already exactly the same you seem to want it to do, I don't understand why you need to add the "only make it scroll when hovered". Scrollbars also hide when the mouse isn't hovered. It seems like that entire logic is unnecessary. That is what I am saying.

Put it otherwise: what is exactly that is not working if you completely remove this hover-checking logic? Because it seems to me it works exactly as you're describing it anyway (and, I suspect, this logic may actually break things, but I haven't really checked it in action as there is no sample that could highlight it)

PS: don't mark a conversation as resolved unless it _is_ resolved, makes it very hard to find again

2023-08-03 11:14 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/TabStrip.kt
> +        Modifier
It really feels like there is something in Compose trying to stop you from doing something you're not supposed to, here  😅

2023-08-03 13:41 UTC, fscarponi commented on core/src/main/kotlin/org/jetbrains/jewel/TabStrip.kt
> +                .fillMaxWidth()
ok, now i got what you were trying to explain!

2023-08-03 13:44 UTC, rock3r commented on core/src/main/kotlin/org/jetbrains/jewel/TabStrip.kt
> +                .fillMaxWidth()
Sorry I didn't explain it too well before 😅

2023-08-03 15:34 UTC, merged